#ifndef SERVER_FILTER_FILTER_INIT_H_
#define SERVER_FILTER_FILTER_INIT_H_

bool CPacketFilterInit();
bool NSSessionPcProcessFilterInit();
bool CNSSessionPcFilterInit();
bool CNSDbManagerFilterInit();
bool CNSPcFilterInit();
bool CNSQuestParamsFilterInit();
bool CNSCriticalSectionFilterInit();
bool CMsgCounterFilterInit();
bool CNSWorldManagerFilterInit();
bool CNSNpcManagerFilterInit();
bool CNSSkillParamsFilterInit();
bool CNSAuctionFilterInit();
bool CNSMsgParamsFilterInit();
bool CNSPcManagerFilterInit();
bool CNSDbLogManagerFilterInit();
bool CNSWareHouseFilterInit();
bool CNSGuildFilterInit();
bool CNSPcParamsFilterInit();
bool CNSPcTitleListFilterInit();
bool COdbcFilterInit();
bool CNSNpcParamsFilterInit();
bool CNSNpcFilterInit();
bool CNSMapManagerFilterInit();
bool NSScriptFilterInit();
bool NSPublicFilterInit();
bool CNSVrBlockManagerFilterInit();
bool CNSCharacterFilterInit();
bool CNSSkillListFilterInit();
bool CIOCompletionWorkerFilterInit();
bool CSessionFilterInit();
bool CMsgCounterFilterInit();
bool CNSSkillFilterInit();
bool CNSNpcStateMoveFilterInit();
bool COutputFileFilterInit();
bool NSUtilityFilterInit();

#endif