// NUMERICAL DESIGN LIMITED PROPRIETARY INFORMATION
//
// This software is supplied under the terms of a license agreement or
// nondisclosure agreement with Numerical Design Limited and may not 
// be copied or disclosed except in accordance with the terms of that 
// agreement.
//
//      Copyright (c) 1996-2004 Numerical Design Limited.
//      All Rights Reserved.
//
// Numerical Design Limited, Chapel Hill, North Carolina 27514
// http://www.ndl.com

#ifndef NIMAIN_H
#define NIMAIN_H

// sets up for DLL import (if desired)
#include "NiMainLibType.h"

#include "NiAccumulator.h"
#include "NiAlphaAccumulator.h"
#include "NiAlphaProperty.h"
#include "NiAmbientLight.h"
#include "NiAVObject.h"
#include "NiBackToFrontAccumulator.h"
#include "NiBillboardNode.h"
#include "NiBinaryExtraData.h"
#include "NiBltSource.h"
#include "NiBMPReader.h"
#include "NiBool.h"
#include "NiBooleanExtraData.h"
#include "NiBound.h"
#include "NiBSPNode.h"
#include "NiCamera.h"
#include "NiClone.h"
#include "NiCloningProcess.h"
#include "NiCollisionObject.h"
#include "NiColor.h"
#include "NiColorExtraData.h"
#include "NiDDSReader.h"
#include "NiDefaultAVObjectPalette.h"
#include "NiDevImageConverter.h"
#include "NiDirectionalLight.h"
#include "NiDitherProperty.h"
#include "NiDynamicEffect.h"
#include "NiDynamicEffectState.h"
#include "NiExtraData.h"
#include "NiFlags.h"
#include "NiFloatExtraData.h"
#include "NiFloatsExtraData.h"
#include "NiFogProperty.h"
#include "NiGeometry.h"
#include "NiGeometryData.h"
#include "NiImageConverter.h"
#include "NiImageReader.h"
#include "NiIntegerExtraData.h"
#include "NiIntegersExtraData.h"
#include "NiLight.h"
#include "NiLines.h"
#include "NiLinesData.h"
#include "NiLODData.h"
#include "NiLODNode.h"
#include "NiMainSDM.h"
#include "NiMaterialProperty.h"
#include "NiMath.h"
#include "NiMatrix3.h"
#include "NiNIFImageReader.h"
#include "NiNode.h"
#include "NiObject.h"
#include "NiObjectNET.h"
#include "NiPalette.h"
#include "NiParticleMeshes.h"
#include "NiParticleMeshesData.h"
#include "NiParticles.h"
#include "NiParticlesData.h"
#include "NiPixelData.h"
#include "NiPixelFormat.h"
#include "NiPlane.h"
#include "NiPoint2.h"
#include "NiPoint3.h"
#include "NiPointLight.h"
#include "NiProcessor.h"
#include "NiProfile.h"
#include "NiProperty.h"
#include "NiPropertyState.h"
#include "NiQuaternion.h"
#include "NiRangeLODData.h"
#include "NiRect.h"
#include "NiRefObject.h"
#include "NiRenderedCubeMap.h"
#include "NiRenderedTexture.h"
#include "NiRenderer.h"
#include "NiRendererSpecificProperty.h"
#include "NiRTTI.h"
#include "NiScreenGeometry.h"
#include "NiScreenGeometryData.h"
#include "NiScreenLODData.h"
#include "NiScreenPolygon.h"
#include "NiScreenSpaceCamera.h"
#include "NiScreenTexture.h"
#include "NiSGIReader.h"
#include "NiShadeProperty.h"

#if defined(WIN32) || defined(_XBOX) || defined(_XENON)
#include "NiSCMExtraData.h"
#include "NiShader.h"
#include "NiShaderAttributeDesc.h"
#include "NiShaderDesc.h"
#include "NiShaderDescBase.h"
#include "NiShaderError.h"
#include "NiShaderFactory.h"
#include "NiShaderLibrary.h"
#include "NiShaderLibraryDesc.h"
#include "NiShaderRequirementDesc.h"
#endif  //#if defined(WIN32) || defined(_XBOX) || defined(_XENON)

#include "NiSkinData.h"
#include "NiSkinInstance.h"
#include "NiSkinPartition.h"
#include "NiSmartPointer.h"
#include "NiSortAdjustNode.h"
#include "NiSourceCubeMap.h"
#include "NiSourceTexture.h"
#include "NiSpecularProperty.h"
#include "NiSpotLight.h"
#include "NiStencilProperty.h"
#include "NiStopWatch.h"
#include "NiStream.h"
#include "NiStreamMacros.h"
#include "NiStringExtraData.h"
#include "NiStringsExtraData.h"
#include "NiSwitchNode.h"
#include "NiSwitchStringExtraData.h"
#include "NiTArray.h"
#include "NiTexture.h"
#include "NiTextureAccumulator.h"
#include "NiTextureCodec.h"
#include "NiTextureEffect.h"
#include "NiTexturePalette.h"
#include "NiTextureTransform.h"
#include "NiTexturingProperty.h"
#include "NiTGAReader.h"
#include "NiTimeController.h"
#include "NiTList.h"
#include "NiTMap.h"
#include "NiTObjectList.h"
#include "NiTPointerList.h"
#include "NiTPointerMap.h"
#include "NiTPool.h"
#include "NiTransform.h"
#include "NiTQueue.h"
#include "NiTriBasedGeom.h"
#include "NiTriBasedGeomData.h"
#include "NiTriShape.h"
#include "NiTriShapeData.h"
#include "NiTriShapeDynamicData.h"
#include "NiTriStrips.h"
#include "NiTriStripsData.h"
#include "NiTSet.h"
#include "NiTStringMap.h"
#include "NiVectorExtraData.h"
#include "NiVertexColorProperty.h"
#include "NiVertWeightsExtraData.h"
#include "NiViewerStrings.h"
#include "NiWireframeProperty.h"
#include "NiZBufferProperty.h"

#if defined(WIN32) || defined(_XBOX) || defined(_XENON)
#include "NiGeometryGroupManager.h"
#endif // defined(WIN32) || defined(_XBOX) || defined(_XENON)

#endif

