#ifndef NSHEADER_NS_SCRIPT_H_
#define NSHEADER_NS_SCRIPT_H_

class CNSPcExt;
class CNSNpcExt;

namespace NSScript {

int NSScriptProductList(lua_State *);    PATCH_STATIC(int, NSScriptProductList, lua_State *, 0x4A1090);
int NSScriptGetPetExpPercent(lua_State *);    PATCH_STATIC(int, NSScriptGetPetExpPercent, lua_State *, 0x4A6250);
int NSScriptCheckQuest(lua_State *);    PATCH_STATIC(int, NSScriptCheckQuest, lua_State *, 0x49ED00);
int NSScriptGetGuildMemberLevel(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildMemberLevel, lua_State *, 0x4A7A90);
int NSScriptIsTimeOut(lua_State *);    PATCH_STATIC(int, NSScriptIsTimeOut, lua_State *, 0x49F5E0);
int NSScriptGiveNeoSteam(lua_State *);    PATCH_STATIC(int, NSScriptGiveNeoSteam, lua_State *, 0x4A0590);
int NSScriptGiveGear(lua_State *);    PATCH_STATIC(int, NSScriptGiveGear, lua_State *, 0x4AA7D0);
int NSScriptCheckEquipItem(lua_State *);    PATCH_STATIC(int, NSScriptCheckEquipItem, lua_State *, 0x49FA20);
int NSScriptOfflineAutoSkillSave(lua_State *);    PATCH_STATIC(int, NSScriptOfflineAutoSkillSave, lua_State *, 0x4AA5D0);
int NSScriptAddExp(lua_State *);    PATCH_STATIC(int, NSScriptAddExp, lua_State *, 0x49FBF0);
int NSScriptSetQuestComplete(lua_State *);    PATCH_STATIC(int, NSScriptSetQuestComplete, lua_State *, 0x49E460);
int NSScriptHitPartyBuff(lua_State *);    PATCH_STATIC(int, NSScriptHitPartyBuff, lua_State *, 0x4A9FE0);
int NSScriptGetGuildMemberCount(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildMemberCount, lua_State *, 0x4A79C0);
int NSScriptGetQuestComplete(lua_State *);    PATCH_STATIC(int, NSScriptGetQuestComplete, lua_State *, 0x49E390);
int NSScriptRecombinationStart(lua_State *);    PATCH_STATIC(int, NSScriptRecombinationStart, lua_State *, 0x4A5CC0);
int NSScriptAddRectInPcRealmPoint(lua_State *);    PATCH_STATIC(int, NSScriptAddRectInPcRealmPoint, lua_State *, 0x4A3C20);
int NSScriptGetStep(lua_State *);    PATCH_STATIC(int, NSScriptGetStep, lua_State *, 0x49E6E0);
int NSScriptSetStep(lua_State *);    PATCH_STATIC(int, NSScriptSetStep, lua_State *, 0x49E890);
int NSScriptNpcInit(lua_State *, CNSNpc *);    PATCH_STATIC(int, NSScriptNpcInit, lua_State * _COMMA CNSNpc *, 0x4AAF40);
int NSScriptGuildCreate(lua_State *);    PATCH_STATIC(int, NSScriptGuildCreate, lua_State *, 0x4A7770);
int NSScriptAddRectInPcExpPoint(lua_State *);    PATCH_STATIC(int, NSScriptAddRectInPcExpPoint, lua_State *, 0x4A3D80);
int NSScriptGetOldFortressRealm(lua_State *);    PATCH_STATIC(int, NSScriptGetOldFortressRealm, lua_State *, 0x4A97D0);
int NSScriptAddPoint(lua_State *);    PATCH_STATIC(int, NSScriptAddPoint, lua_State *, 0x49EA60);
int NSScriptCheckCompleteStep(lua_State *);    PATCH_STATIC(int, NSScriptCheckCompleteStep, lua_State *, 0x49E610);
int NSScriptSteamCoreDestroy2(lua_State *);    PATCH_STATIC(int, NSScriptSteamCoreDestroy2, lua_State *, 0x4A4B70);
int NSScriptSteamCoreDestroy3(lua_State *);    PATCH_STATIC(int, NSScriptSteamCoreDestroy3, lua_State *, 0x4A4D00);
int NSScriptAddGuildPremiumItem(lua_State *);    PATCH_STATIC(int, NSScriptAddGuildPremiumItem, lua_State *, 0x4A85F0);
int NSScriptSteamCoreDestroy(lua_State *);    PATCH_STATIC(int, NSScriptSteamCoreDestroy, lua_State *, 0x4A49E0);
int NSScriptMakeBlockLarge(lua_State *);    PATCH_STATIC(int, NSScriptMakeBlockLarge, lua_State *, 0x4A9200);
int NSScriptAttackRectInNpc(lua_State *);    PATCH_STATIC(int, NSScriptAttackRectInNpc, lua_State *, 0x4A3F30);
int NSScriptTameMobExist(lua_State *);    PATCH_STATIC(int, NSScriptTameMobExist, lua_State *, 0x4A0D30);
int NSScriptReserveStart(lua_State *);    PATCH_STATIC(int, NSScriptReserveStart, lua_State *, 0x4AA7E0);
int NSScriptMakeBlockMiniRVR(lua_State *);    PATCH_STATIC(int, NSScriptMakeBlockMiniRVR, lua_State *, 0x4A9350);
int NSScriptGetPoint(lua_State *);    PATCH_STATIC(int, NSScriptGetPoint, lua_State *, 0x49EB50);
int NSScriptWarp(lua_State *);    PATCH_STATIC(int, NSScriptWarp, lua_State *, 0x4A1280);
int NSScriptWarpNpc(lua_State *);    PATCH_STATIC(int, NSScriptWarpNpc, lua_State *, 0x4A19D0);
int NSScriptAddItem2(lua_State *);    PATCH_STATIC(int, NSScriptAddItem2, lua_State *, 0x4A0170);
int NSScriptWarpGuild(lua_State *);    PATCH_STATIC(int, NSScriptWarpGuild, lua_State *, 0x4A18F0);
int NSScriptChangeBindPos(lua_State *);    PATCH_STATIC(int, NSScriptChangeBindPos, lua_State *, 0x4A0C00);
int NSScriptEffectSkillCast(lua_State *);    PATCH_STATIC(int, NSScriptEffectSkillCast, lua_State *, 0x4AA1F0);
int NSScriptAddSkillExp(lua_State *);    PATCH_STATIC(int, NSScriptAddSkillExp, lua_State *, 0x4A87F0);
int NSScriptBroadcastRealmTitle(lua_State *);    PATCH_STATIC(int, NSScriptBroadcastRealmTitle, lua_State *, 0x4A7180);
int NSScriptRectInDisappearNpc(lua_State *);    PATCH_STATIC(int, NSScriptRectInDisappearNpc, lua_State *, 0x4A2D20);
int NSScriptRectInDisappearNpc2(lua_State *);    PATCH_STATIC(int, NSScriptRectInDisappearNpc2, lua_State *, 0x4A3470);
int NSScriptDeleteBlock(lua_State *);    PATCH_STATIC(int, NSScriptDeleteBlock, lua_State *, 0x4A6820);
int NSScriptWarpAndStun(lua_State *);    PATCH_STATIC(int, NSScriptWarpAndStun, lua_State *, 0x4A24B0);
int NSScriptGetNsMaxCharge(lua_State *);    PATCH_STATIC(int, NSScriptGetNsMaxCharge, lua_State *, 0x4A0720);
int NSScriptAttackRectInPc(lua_State *);    PATCH_STATIC(int, NSScriptAttackRectInPc, lua_State *, 0x4A4560);
int NSScriptIsGuildMaster(lua_State *);    PATCH_STATIC(int, NSScriptIsGuildMaster, lua_State *, 0x4A7C60);
int NSScriptDisappear(lua_State *);    PATCH_STATIC(int, NSScriptDisappear, lua_State *, 0x4A4970);
int NSScriptCallMob(lua_State *);    PATCH_STATIC(int, NSScriptCallMob, lua_State *, 0x49EF40);
int NSScriptNpcFuncExist(lua_State *, char *);    PATCH_STATIC(int, NSScriptNpcFuncExist, lua_State * _COMMA char *, 0x4AE660);
int NSScriptAddRectInPcItem(lua_State *);    PATCH_STATIC(int, NSScriptAddRectInPcItem, lua_State *, 0x4A29D0);
int NSScriptAddItem3(lua_State *);    PATCH_STATIC(int, NSScriptAddItem3, lua_State *, 0x4A0340);
int NSScriptIsPartyMember(lua_State *);    PATCH_STATIC(int, NSScriptIsPartyMember, lua_State *, 0x4A65A0);
int NSScriptSkillLevelUp(lua_State *);    PATCH_STATIC(int, NSScriptSkillLevelUp, lua_State *, 0x49E1D0);
int NSScriptPVPTournamentEnd(lua_State *);    PATCH_STATIC(int, NSScriptPVPTournamentEnd, lua_State *, 0x4A9620);
int NSScriptUpgradeStart(lua_State *);    PATCH_STATIC(int, NSScriptUpgradeStart, lua_State *, 0x4A5B90);
int NSScriptTameMobInsert(lua_State *);    PATCH_STATIC(int, NSScriptTameMobInsert, lua_State *, 0x4A0EF0);
int NSScriptChangePetLevel(lua_State *);    PATCH_STATIC(int, NSScriptChangePetLevel, lua_State *, 0x4A62E0);
int NSScriptGetRectInMyParty(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInMyParty, lua_State *, 0x4A3A90);
int NSScriptGetSkillLevel(lua_State *);    PATCH_STATIC(int, NSScriptGetSkillLevel, lua_State *, 0x49DED0);
int NSScriptNpcIdle(lua_State *, CNSNpc *, char *);    PATCH_STATIC(int, NSScriptNpcIdle, lua_State * _COMMA CNSNpc * _COMMA char *, 0x4AE6D0);
int NSScriptGetGuildRankMonth(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildRankMonth, lua_State *, 0x4A82F0);
int NSScriptGetInvenSpace(lua_State *);    PATCH_STATIC(int, NSScriptGetInvenSpace, lua_State *, 0x4A0930);
int NSScriptChangeGuildMark(lua_State *);    PATCH_STATIC(int, NSScriptChangeGuildMark, lua_State *, 0x4A84B0);
int NSScriptChangeJob(lua_State *);    PATCH_STATIC(int, NSScriptChangeJob, lua_State *, 0x4A09D0);
int NSScriptAddShopItem2(lua_State *);    PATCH_STATIC(int, NSScriptAddShopItem2, lua_State *, 0x49DB00);
int NSScriptRVREnd(lua_State *);    PATCH_STATIC(int, NSScriptRVREnd, lua_State *, 0x4A9590);
int NSScriptGetFortressRealm(lua_State *);    PATCH_STATIC(int, NSScriptGetFortressRealm, lua_State *, 0x4A96D0);
int NSScriptSetFortressRealm(lua_State *);    PATCH_STATIC(int, NSScriptSetFortressRealm, lua_State *, 0x4A9750);
int NSScriptIsEquipRemoveAll(lua_State *);    PATCH_STATIC(int, NSScriptIsEquipRemoveAll, lua_State *, 0x4A0AA0);
int NSScriptCheckCurrentRVREnd(lua_State *);    PATCH_STATIC(int, NSScriptCheckCurrentRVREnd, lua_State *, 0x4A9690);
int NSScriptGetNsCharge(lua_State *);    PATCH_STATIC(int, NSScriptGetNsCharge, lua_State *, 0x4A0670);
int NSScriptDialogOpen(lua_State *);    PATCH_STATIC(int, NSScriptDialogOpen, lua_State *, 0x4A58B0);
int NSScriptEventStart(lua_State *);    PATCH_STATIC(int, NSScriptEventStart, lua_State *, 0x4A5780);
int NSScriptGetZoneInfo(lua_State *);    PATCH_STATIC(int, NSScriptGetZoneInfo, lua_State *, 0x4A98D0);
int NSScriptBroadcastBuff(lua_State *);    PATCH_STATIC(int, NSScriptBroadcastBuff, lua_State *, 0x4A9EF0);
int NSScriptPartyAvrLevel(lua_State *);    PATCH_STATIC(int, NSScriptPartyAvrLevel, lua_State *, 0x4A6630);
int NSScriptDeleteItem(lua_State *);    PATCH_STATIC(int, NSScriptDeleteItem, lua_State *, 0x4A07B0);
int NSScriptNeoSlotCoinAdd(lua_State *);    PATCH_STATIC(int, NSScriptNeoSlotCoinAdd, lua_State *, 0x4AA370);
int NSScriptPetRebirth(lua_State *);    PATCH_STATIC(int, NSScriptPetRebirth, lua_State *, 0x4A6130);
int NSScriptChangeGuildLevel(lua_State *);    PATCH_STATIC(int, NSScriptChangeGuildLevel, lua_State *, 0x4A7B60);
int NSScriptGetGearInfo(lua_State *);    PATCH_STATIC(int, NSScriptGetGearInfo, lua_State *, 0x4AA730);
int NSScriptDisappearNpc(lua_State *);    PATCH_STATIC(int, NSScriptDisappearNpc, lua_State *, 0x4A6950);
int NSScriptLogout(lua_State *);    PATCH_STATIC(int, NSScriptLogout, lua_State *, 0x4AA660);
int NSScriptGetServerMinute(lua_State *);    PATCH_STATIC(int, NSScriptGetServerMinute, lua_State *, 0x49F7B0);
int NSScriptItemMining(lua_State *);    PATCH_STATIC(int, NSScriptItemMining, lua_State *, 0x4A5170);
int NSScriptTameMobSave(lua_State *);    PATCH_STATIC(int, NSScriptTameMobSave, lua_State *, 0x4A0E50);
int NSScriptGetRectInPcAvrLevel(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInPcAvrLevel, lua_State *, 0x4A2EB0);
int NSScriptHealRectInNpc(lua_State *);    PATCH_STATIC(int, NSScriptHealRectInNpc, lua_State *, 0x4A4400);
int NSScriptPetMessage(lua_State *);    PATCH_STATIC(int, NSScriptPetMessage, lua_State *, 0x4A64D0);
int NSScriptItemAutoMining(lua_State *);    PATCH_STATIC(int, NSScriptItemAutoMining, lua_State *, 0x4A52A0);
int NSScriptGetGuildPremiumItemDays(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildPremiumItemDays, lua_State *, 0x4A86F0);
int NSScriptSetShopRate(lua_State *);    PATCH_STATIC(int, NSScriptSetShopRate, lua_State *, 0x49DCB0);
int NSScriptWarpBind(lua_State *);    PATCH_STATIC(int, NSScriptWarpBind, lua_State *, 0x4A2160);
int NSScriptPcTitleIsExist(lua_State *);    PATCH_STATIC(int, NSScriptPcTitleIsExist, lua_State *, 0x4AADE0);
int NSScriptPcTitleGetCount(lua_State *);    PATCH_STATIC(int, NSScriptPcTitleGetCount, lua_State *, 0x4AAEA0);
int NSScriptHealRectInPersonalSiegeWeapon(lua_State *);    PATCH_STATIC(int, NSScriptHealRectInPersonalSiegeWeapon, lua_State *, 0x4A3730);
int NSScriptBroadcastBuff2(lua_State *);    PATCH_STATIC(int, NSScriptBroadcastBuff2, lua_State *, 0x4A9FA0);
int NSScriptIsAggro(lua_State *);    PATCH_STATIC(int, NSScriptIsAggro, lua_State *, 0x49D8C0);
int NSScriptPVPTournamentStart(lua_State *);    PATCH_STATIC(int, NSScriptPVPTournamentStart, lua_State *, 0x4A95F0);
void NSScriptEnd(lua_State *);    PATCH_STATIC(void, NSScriptEnd, lua_State *, 0x49D460);
int NSScriptAutoSkill(lua_State *);    PATCH_STATIC(int, NSScriptAutoSkill, lua_State *, 0x4A8DE0);
int NSScriptAddExpHitLastPc(lua_State *);    PATCH_STATIC(int, NSScriptAddExpHitLastPc, lua_State *, 0x4AAB80);
int NSScriptGetRectInPcCount2(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInPcCount2, lua_State *, 0x4A3010);
int NSScriptGetRectInPcCount(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInPcCount, lua_State *, 0x4A2840);
int NSScriptWareHouseList(lua_State *);    PATCH_STATIC(int, NSScriptWareHouseList, lua_State *, 0x4A88D0);
int NSScriptPcTitleAdd(lua_State *);    PATCH_STATIC(int, NSScriptPcTitleAdd, lua_State *, 0x4AACF0);
int NSScriptSelfBuff(lua_State *);    PATCH_STATIC(int, NSScriptSelfBuff, lua_State *, 0x4A9D90);
int NSScriptReserveIsStart(lua_State *);    PATCH_STATIC(int, NSScriptReserveIsStart, lua_State *, 0x4AA910);
int NSScriptGetLocalTime(lua_State *);    PATCH_STATIC(int, NSScriptGetLocalTime, lua_State *, 0x49F800);
int NSScriptGetRectInNpcCount(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInNpcCount, lua_State *, 0x4A2B90);
int NSScriptGetItemCount(lua_State *);    PATCH_STATIC(int, NSScriptGetItemCount, lua_State *, 0x49E2B0);
int NSScriptNpcQuestCheck(lua_State *, CNSNpc *, CNSPc *);    PATCH_STATIC(int, NSScriptNpcQuestCheck, lua_State * _COMMA CNSNpc * _COMMA CNSPc *, 0x4AF970);
int NSScriptGetRemainTime(lua_State *);    PATCH_STATIC(int, NSScriptGetRemainTime, lua_State *, 0x49E530);
int NSScriptReserveWarp(lua_State *);    PATCH_STATIC(int, NSScriptReserveWarp, lua_State *, 0x4AAAF0);
int NSScriptWarpAndBind(lua_State *);    PATCH_STATIC(int, NSScriptWarpAndBind, lua_State *, 0x4A1470);
int NSScriptPanic(lua_State *);    PATCH_STATIC(int, NSScriptPanic, lua_State *, 0x49D330);
int NSScriptReserveAdd(lua_State *);    PATCH_STATIC(int, NSScriptReserveAdd, lua_State *, 0x4AA970);
int NSScriptGetRealmPoint(lua_State *);    PATCH_STATIC(int, NSScriptGetRealmPoint, lua_State *, 0x49FDD0);
int NSScriptNpcTalk(lua_State *, CNSNpc *, CNSPcExt *, char *, CPacket &);    PATCH_STATIC(int, NSScriptNpcTalk, lua_State * _COMMA CNSNpcExt * _COMMA CNSPcExt * _COMMA char * _COMMA CPacket &, 0x4AB2E0);
int NSScriptWareHouseSort(lua_State *);    PATCH_STATIC(int, NSScriptWareHouseSort, lua_State *, 0x4A8980);
int NSScriptReserveDelete(lua_State *);    PATCH_STATIC(int, NSScriptReserveDelete, lua_State *, 0x4AAA30);
int NSScriptPSWFactory(lua_State *);    PATCH_STATIC(int, NSScriptPSWFactory, lua_State *, 0x4A94A0);
int NSScriptRVRStart(lua_State *);    PATCH_STATIC(int, NSScriptRVRStart, lua_State *, 0x4A9570);
int NSScriptAwakeRectInNpc(lua_State *);    PATCH_STATIC(int, NSScriptAwakeRectInNpc, lua_State *, 0x4A4090);
int NSScriptIsPVEServerMode(lua_State *);    PATCH_STATIC(int, NSScriptIsPVEServerMode, lua_State *, 0x4A9890);
int NSScriptGuildClose(lua_State *);    PATCH_STATIC(int, NSScriptGuildClose, lua_State *, 0x4A7830);
int NSScriptWarpArea2(lua_State *);    PATCH_STATIC(int, NSScriptWarpArea2, lua_State *, 0x4A1E20);
int NSScriptGetRectInNpcHpPercent(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInNpcHpPercent, lua_State *, 0x49D760);
int NSScriptWarpArea(lua_State *);    PATCH_STATIC(int, NSScriptWarpArea, lua_State *, 0x4A1AB0);
int NSScriptAutoRectInPartyJoin(lua_State *);    PATCH_STATIC(int, NSScriptAutoRectInPartyJoin, lua_State *, 0x4A4810);
int NSScriptGetGuildMemberRank(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildMemberRank, lua_State *, 0x4A7D30);
int NSScriptIsRVRServerMode(lua_State *);    PATCH_STATIC(int, NSScriptIsRVRServerMode, lua_State *, 0x4A9850);
int NSScriptAddItem(lua_State *);    PATCH_STATIC(int, NSScriptAddItem, lua_State *, 0x4A0010);
int NSScriptPartyMemberCount(lua_State *);    PATCH_STATIC(int, NSScriptPartyMemberCount, lua_State *, 0x4A66F0);
int NSScriptSetTargetNpc(lua_State *);    PATCH_STATIC(int, NSScriptSetTargetNpc, lua_State *, 0x49DC00);
int NSScriptAddRealmPoint(lua_State *);    PATCH_STATIC(int, NSScriptAddRealmPoint, lua_State *, 0x49FE70);
int NSScriptPrintGuildLog(lua_State *);    PATCH_STATIC(int, NSScriptPrintGuildLog, lua_State *, 0x4A7E00);
int NSScriptGiveRealmPoint(lua_State *);    PATCH_STATIC(int, NSScriptGiveRealmPoint, lua_State *, 0x49FF40);
lua_State * NSScriptInit(unsigned short);    PATCH_STATIC(lua_State *, NSScriptInit, unsigned short, 0x49D3A0);
lua_State * NSScriptInit();    PATCH_STATIC(lua_State *, NSScriptInit, , 0x49D350);
int NSScriptAddSkill(lua_State *);    PATCH_STATIC(int, NSScriptAddSkill, lua_State *, 0x49E080);
int NSScriptGetRectInNpcCount2(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInNpcCount2, lua_State *, 0x4A3310);
int NSScriptSkillReset(lua_State *);    PATCH_STATIC(int, NSScriptSkillReset, lua_State *, 0x4A8A90);
int NSScriptSetClear(lua_State *);    PATCH_STATIC(int, NSScriptSetClear, lua_State *, 0x49E990);
int NSScriptHitRectInPcDebuff(lua_State *);    PATCH_STATIC(int, NSScriptHitRectInPcDebuff, lua_State *, 0x4A38C0);
int NSScriptRideSiegeWeapon(lua_State *);    PATCH_STATIC(int, NSScriptRideSiegeWeapon, lua_State *, 0x4A9010);
int NSScriptIsRVRStart(lua_State *);    PATCH_STATIC(int, NSScriptIsRVRStart, lua_State *, 0x4A95B0);
int NSScriptItemUnlock(lua_State *);    PATCH_STATIC(int, NSScriptItemUnlock, lua_State *, 0x4A5430);
int NSScriptNeoSlotCoinCount(lua_State *);    PATCH_STATIC(int, NSScriptNeoSlotCoinCount, lua_State *, 0x4AA430);
int NSScriptBroadcastCenter(lua_State *);    PATCH_STATIC(int, NSScriptBroadcastCenter, lua_State *, 0x4A6D50);
int NSScriptGiveGuildPoint(lua_State *);    PATCH_STATIC(int, NSScriptGiveGuildPoint, lua_State *, 0x4A81A0);
int NSScriptSkillChange(lua_State *);    PATCH_STATIC(int, NSScriptSkillChange, lua_State *, 0x4A8C60);
int NSScriptCheckTimeOut(lua_State *);    PATCH_STATIC(int, NSScriptCheckTimeOut, lua_State *, 0x49F500);
int NSScriptUpgradePet(lua_State *);    PATCH_STATIC(int, NSScriptUpgradePet, lua_State *, 0x4A6400);
int NSScriptAddNeoSteam(lua_State *);    PATCH_STATIC(int, NSScriptAddNeoSteam, lua_State *, 0x4A04A0);
int NSScriptBroadcast(lua_State *);    PATCH_STATIC(int, NSScriptBroadcast, lua_State *, 0x4A6A30);
void NSScriptPrintStackStatus(lua_State *);    PATCH_STATIC(void, NSScriptPrintStackStatus, lua_State *, 0x49D480);
int NSScriptSetTimeOut(lua_State *);    PATCH_STATIC(int, NSScriptSetTimeOut, lua_State *, 0x49F400);
int NSScriptCheckItem(lua_State *);    PATCH_STATIC(int, NSScriptCheckItem, lua_State *, 0x49F860);
int NSScriptNpcLoad(lua_State *, unsigned short);    PATCH_STATIC(int, NSScriptNpcLoad, lua_State * _COMMA unsigned short, 0x49D650);
int NSScriptChangeRace(lua_State *);    PATCH_STATIC(int, NSScriptChangeRace, lua_State *, 0x4A0B30);
int NSScriptGetDescriptNpc(lua_State *);    PATCH_STATIC(int, NSScriptGetDescriptNpc, lua_State *, 0x4A5DF0);
int NSScriptSetNextStep(lua_State *);    PATCH_STATIC(int, NSScriptSetNextStep, lua_State *, 0x49E7C0);
int NSScriptDeleteNpc(lua_State *);    PATCH_STATIC(int, NSScriptDeleteNpc, lua_State *, 0x4A67C0);
int NSScriptRidePersonalSiegeWeapon(lua_State *);    PATCH_STATIC(int, NSScriptRidePersonalSiegeWeapon, lua_State *, 0x4A9160);
int NSScriptGetServerHour(lua_State *);    PATCH_STATIC(int, NSScriptGetServerHour, lua_State *, 0x49F760);
int NSScriptGetHpPercent(lua_State *);    PATCH_STATIC(int, NSScriptGetHpPercent, lua_State *, 0x49D6D0);
int NSScriptGetStartSecond(lua_State *);    PATCH_STATIC(int, NSScriptGetStartSecond, lua_State *, 0x4AA2D0);
int NSScriptWarpAndClarity(lua_State *);    PATCH_STATIC(int, NSScriptWarpAndClarity, lua_State *, 0x4A2720);
int NSScriptIsExistSkill(lua_State *);    PATCH_STATIC(int, NSScriptIsExistSkill, lua_State *, 0x49DFB0);
int NSScriptIsMaxExp(lua_State *);    PATCH_STATIC(int, NSScriptIsMaxExp, lua_State *, 0x49EEB0);
int NSScriptReserveEnd(lua_State *);    PATCH_STATIC(int, NSScriptReserveEnd, lua_State *, 0x4AA8B0);
int NSScriptGetDescriptItem(lua_State *);    PATCH_STATIC(int, NSScriptGetDescriptItem, lua_State *, 0x4A5E70);
int NSScriptGetGuildPoint(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildPoint, lua_State *, 0x4A7F80);
int NSScriptChangePet(lua_State *);    PATCH_STATIC(int, NSScriptChangePet, lua_State *, 0x4A6000);
int NSScriptWarpParty(lua_State *);    PATCH_STATIC(int, NSScriptWarpParty, lua_State *, 0x4A1810);
int NSScriptGiveGold(lua_State *);    PATCH_STATIC(int, NSScriptGiveGold, lua_State *, 0x49FAF0);
int NSScriptBroadcastRealm(lua_State *);    PATCH_STATIC(int, NSScriptBroadcastRealm, lua_State *, 0x4A7050);
int NSScriptOfflineAutoSkillLoad(lua_State *);    PATCH_STATIC(int, NSScriptOfflineAutoSkillLoad, lua_State *, 0x4AA4C0);
int NSScriptClearTimeOut(lua_State *);    PATCH_STATIC(int, NSScriptClearTimeOut, lua_State *, 0x49F6B0);
int NSScriptIsPVPTournamentStart(lua_State *);    PATCH_STATIC(int, NSScriptIsPVPTournamentStart, lua_State *, 0x4A9650);
int NSScriptGetPcZoneInfo(lua_State *);    PATCH_STATIC(int, NSScriptGetPcZoneInfo, lua_State *, 0x4A99A0);
int NSScriptLevelUp100(lua_State *);    PATCH_STATIC(int, NSScriptLevelUp100, lua_State *, 0x49EDD0);
int NSScriptGetRectInSiegeWeaponCount(lua_State *);    PATCH_STATIC(int, NSScriptGetRectInSiegeWeaponCount, lua_State *, 0x4A35D0);
int NSScriptMaterialList(lua_State *);    PATCH_STATIC(int, NSScriptMaterialList, lua_State *, 0x4A0FB0);
int NSScriptCheckNpc(lua_State *);    PATCH_STATIC(int, NSScriptCheckNpc, lua_State *, 0x4A69B0);
int NSScriptResolutionStart(lua_State *);    PATCH_STATIC(int, NSScriptResolutionStart, lua_State *, 0x4A5A60);
int NSScriptCallNpc(lua_State *);    PATCH_STATIC(int, NSScriptCallNpc, lua_State *, 0x49F300);
int NSScriptGetRiderId(lua_State *);    PATCH_STATIC(int, NSScriptGetRiderId, lua_State *, 0x4A8F70);
int NSScriptAddGuildPoint(lua_State *);    PATCH_STATIC(int, NSScriptAddGuildPoint, lua_State *, 0x4A8060);
int NSScriptGetHitLastPcRealm(lua_State *);    PATCH_STATIC(int, NSScriptGetHitLastPcRealm, lua_State *, 0x4AAC60);
int NSScriptItemGathering(lua_State *);    PATCH_STATIC(int, NSScriptItemGathering, lua_State *, 0x4A4E90);
int NSScriptLevelUpRectInPc(lua_State *);    PATCH_STATIC(int, NSScriptLevelUpRectInPc, lua_State *, 0x4A46F0);
int NSScriptBroadcastNotify(lua_State *);    PATCH_STATIC(int, NSScriptBroadcastNotify, lua_State *, 0x4A72C0);
int NSScriptTameMobLoad(lua_State *);    PATCH_STATIC(int, NSScriptTameMobLoad, lua_State *, 0x4A0DC0);
int NSScriptTransferMachine(lua_State *);    PATCH_STATIC(int, NSScriptTransferMachine, lua_State *, 0x4A5EF0);
int NSScriptHitBuff(lua_State *);    PATCH_STATIC(int, NSScriptHitBuff, lua_State *, 0x4A9A60);
int NSScriptAddGold(lua_State *);    PATCH_STATIC(int, NSScriptAddGold, lua_State *, 0x49FCD0);
int NSScriptGetGuildRankMonthName(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildRankMonthName, lua_State *, 0x4A83C0);
int NSScriptGuildList(lua_State *);    PATCH_STATIC(int, NSScriptGuildList, lua_State *, 0x4A76B0);
int NSScriptSkillMake60(lua_State *);    PATCH_STATIC(int, NSScriptSkillMake60, lua_State *, 0x49EE40);
int NSScriptSkillPSWPartReset(lua_State *);    PATCH_STATIC(int, NSScriptSkillPSWPartReset, lua_State *, 0x4A8D40);
int NSScriptIsAdmin(lua_State *);    PATCH_STATIC(int, NSScriptIsAdmin, lua_State *, 0x4A8ED0);
int NSScriptAddQuest(lua_State *);    PATCH_STATIC(int, NSScriptAddQuest, lua_State *, 0x49EC30);
int NSScriptGetGuildLevel(lua_State *);    PATCH_STATIC(int, NSScriptGetGuildLevel, lua_State *, 0x4A78F0);
int NSScriptWarpDelay(lua_State *);    PATCH_STATIC(int, NSScriptWarpDelay, lua_State *, 0x4A2200);
int NSScriptAddShopItem(lua_State *);    PATCH_STATIC(int, NSScriptAddShopItem, lua_State *, 0x49D960);
int NSScriptShopList(lua_State *);    PATCH_STATIC(int, NSScriptShopList, lua_State *, 0x49DDB0);

struct _Invoke {
    PATCH_STATIC_INVOKE(int, NSScriptNpcTalk, lua_State * _COMMA CNSNpc * _COMMA CNSPc * _COMMA char * _COMMA CPacket &);
};


#ifdef DEFINE_NS_CPP
DEFINE_NAKED_JMP(int NSScriptProductList(lua_State *), 0x4A1090);
DEFINE_NAKED_JMP(int NSScriptGetPetExpPercent(lua_State *), 0x4A6250);
DEFINE_NAKED_JMP(int NSScriptCheckQuest(lua_State *), 0x49ED00);
DEFINE_NAKED_JMP(int NSScriptGetGuildMemberLevel(lua_State *), 0x4A7A90);
DEFINE_NAKED_JMP(int NSScriptIsTimeOut(lua_State *), 0x49F5E0);
DEFINE_NAKED_JMP(int NSScriptGiveNeoSteam(lua_State *), 0x4A0590);
DEFINE_NAKED_JMP(int NSScriptGiveGear(lua_State *), 0x4AA7D0);
DEFINE_NAKED_JMP(int NSScriptCheckEquipItem(lua_State *), 0x49FA20);
DEFINE_NAKED_JMP(int NSScriptOfflineAutoSkillSave(lua_State *), 0x4AA5D0);
DEFINE_NAKED_JMP(int NSScriptAddExp(lua_State *), 0x49FBF0);
DEFINE_NAKED_JMP(int NSScriptSetQuestComplete(lua_State *), 0x49E460);
DEFINE_NAKED_JMP(int NSScriptHitPartyBuff(lua_State *), 0x4A9FE0);
DEFINE_NAKED_JMP(int NSScriptGetGuildMemberCount(lua_State *), 0x4A79C0);
DEFINE_NAKED_JMP(int NSScriptGetQuestComplete(lua_State *), 0x49E390);
DEFINE_NAKED_JMP(int NSScriptRecombinationStart(lua_State *), 0x4A5CC0);
DEFINE_NAKED_JMP(int NSScriptAddRectInPcRealmPoint(lua_State *), 0x4A3C20);
DEFINE_NAKED_JMP(int NSScriptGetStep(lua_State *), 0x49E6E0);
DEFINE_NAKED_JMP(int NSScriptSetStep(lua_State *), 0x49E890);
DEFINE_NAKED_JMP(int NSScriptNpcInit(lua_State * _COMMA CNSNpc *), 0x4AAF40);
DEFINE_NAKED_JMP(int NSScriptGuildCreate(lua_State *), 0x4A7770);
DEFINE_NAKED_JMP(int NSScriptAddRectInPcExpPoint(lua_State *), 0x4A3D80);
DEFINE_NAKED_JMP(int NSScriptGetOldFortressRealm(lua_State *), 0x4A97D0);
DEFINE_NAKED_JMP(int NSScriptAddPoint(lua_State *), 0x49EA60);
DEFINE_NAKED_JMP(int NSScriptCheckCompleteStep(lua_State *), 0x49E610);
DEFINE_NAKED_JMP(int NSScriptSteamCoreDestroy2(lua_State *), 0x4A4B70);
DEFINE_NAKED_JMP(int NSScriptSteamCoreDestroy3(lua_State *), 0x4A4D00);
DEFINE_NAKED_JMP(int NSScriptAddGuildPremiumItem(lua_State *), 0x4A85F0);
DEFINE_NAKED_JMP(int NSScriptSteamCoreDestroy(lua_State *), 0x4A49E0);
DEFINE_NAKED_JMP(int NSScriptMakeBlockLarge(lua_State *), 0x4A9200);
DEFINE_NAKED_JMP(int NSScriptAttackRectInNpc(lua_State *), 0x4A3F30);
DEFINE_NAKED_JMP(int NSScriptTameMobExist(lua_State *), 0x4A0D30);
DEFINE_NAKED_JMP(int NSScriptReserveStart(lua_State *), 0x4AA7E0);
DEFINE_NAKED_JMP(int NSScriptMakeBlockMiniRVR(lua_State *), 0x4A9350);
DEFINE_NAKED_JMP(int NSScriptGetPoint(lua_State *), 0x49EB50);
DEFINE_NAKED_JMP(int NSScriptWarp(lua_State *), 0x4A1280);
DEFINE_NAKED_JMP(int NSScriptWarpNpc(lua_State *), 0x4A19D0);
DEFINE_NAKED_JMP(int NSScriptAddItem2(lua_State *), 0x4A0170);
DEFINE_NAKED_JMP(int NSScriptWarpGuild(lua_State *), 0x4A18F0);
DEFINE_NAKED_JMP(int NSScriptChangeBindPos(lua_State *), 0x4A0C00);
DEFINE_NAKED_JMP(int NSScriptEffectSkillCast(lua_State *), 0x4AA1F0);
DEFINE_NAKED_JMP(int NSScriptAddSkillExp(lua_State *), 0x4A87F0);
DEFINE_NAKED_JMP(int NSScriptBroadcastRealmTitle(lua_State *), 0x4A7180);
DEFINE_NAKED_JMP(int NSScriptRectInDisappearNpc(lua_State *), 0x4A2D20);
DEFINE_NAKED_JMP(int NSScriptRectInDisappearNpc2(lua_State *), 0x4A3470);
DEFINE_NAKED_JMP(int NSScriptDeleteBlock(lua_State *), 0x4A6820);
DEFINE_NAKED_JMP(int NSScriptWarpAndStun(lua_State *), 0x4A24B0);
DEFINE_NAKED_JMP(int NSScriptGetNsMaxCharge(lua_State *), 0x4A0720);
DEFINE_NAKED_JMP(int NSScriptAttackRectInPc(lua_State *), 0x4A4560);
DEFINE_NAKED_JMP(int NSScriptIsGuildMaster(lua_State *), 0x4A7C60);
DEFINE_NAKED_JMP(int NSScriptDisappear(lua_State *), 0x4A4970);
DEFINE_NAKED_JMP(int NSScriptCallMob(lua_State *), 0x49EF40);
DEFINE_NAKED_JMP(int NSScriptNpcFuncExist(lua_State * _COMMA char *), 0x4AE660);
DEFINE_NAKED_JMP(int NSScriptAddRectInPcItem(lua_State *), 0x4A29D0);
DEFINE_NAKED_JMP(int NSScriptAddItem3(lua_State *), 0x4A0340);
DEFINE_NAKED_JMP(int NSScriptIsPartyMember(lua_State *), 0x4A65A0);
DEFINE_NAKED_JMP(int NSScriptSkillLevelUp(lua_State *), 0x49E1D0);
DEFINE_NAKED_JMP(int NSScriptPVPTournamentEnd(lua_State *), 0x4A9620);
DEFINE_NAKED_JMP(int NSScriptUpgradeStart(lua_State *), 0x4A5B90);
DEFINE_NAKED_JMP(int NSScriptTameMobInsert(lua_State *), 0x4A0EF0);
DEFINE_NAKED_JMP(int NSScriptChangePetLevel(lua_State *), 0x4A62E0);
DEFINE_NAKED_JMP(int NSScriptGetRectInMyParty(lua_State *), 0x4A3A90);
DEFINE_NAKED_JMP(int NSScriptGetSkillLevel(lua_State *), 0x49DED0);
DEFINE_NAKED_JMP(int NSScriptNpcIdle(lua_State * _COMMA CNSNpc * _COMMA char *), 0x4AE6D0);
DEFINE_NAKED_JMP(int NSScriptGetGuildRankMonth(lua_State *), 0x4A82F0);
DEFINE_NAKED_JMP(int NSScriptGetInvenSpace(lua_State *), 0x4A0930);
DEFINE_NAKED_JMP(int NSScriptChangeGuildMark(lua_State *), 0x4A84B0);
DEFINE_NAKED_JMP(int NSScriptChangeJob(lua_State *), 0x4A09D0);
DEFINE_NAKED_JMP(int NSScriptAddShopItem2(lua_State *), 0x49DB00);
DEFINE_NAKED_JMP(int NSScriptRVREnd(lua_State *), 0x4A9590);
DEFINE_NAKED_JMP(int NSScriptGetFortressRealm(lua_State *), 0x4A96D0);
DEFINE_NAKED_JMP(int NSScriptSetFortressRealm(lua_State *), 0x4A9750);
DEFINE_NAKED_JMP(int NSScriptIsEquipRemoveAll(lua_State *), 0x4A0AA0);
DEFINE_NAKED_JMP(int NSScriptCheckCurrentRVREnd(lua_State *), 0x4A9690);
DEFINE_NAKED_JMP(int NSScriptGetNsCharge(lua_State *), 0x4A0670);
DEFINE_NAKED_JMP(int NSScriptDialogOpen(lua_State *), 0x4A58B0);
DEFINE_NAKED_JMP(int NSScriptEventStart(lua_State *), 0x4A5780);
DEFINE_NAKED_JMP(int NSScriptGetZoneInfo(lua_State *), 0x4A98D0);
DEFINE_NAKED_JMP(int NSScriptBroadcastBuff(lua_State *), 0x4A9EF0);
DEFINE_NAKED_JMP(int NSScriptPartyAvrLevel(lua_State *), 0x4A6630);
DEFINE_NAKED_JMP(int NSScriptDeleteItem(lua_State *), 0x4A07B0);
DEFINE_NAKED_JMP(int NSScriptNeoSlotCoinAdd(lua_State *), 0x4AA370);
DEFINE_NAKED_JMP(int NSScriptPetRebirth(lua_State *), 0x4A6130);
DEFINE_NAKED_JMP(int NSScriptChangeGuildLevel(lua_State *), 0x4A7B60);
DEFINE_NAKED_JMP(int NSScriptGetGearInfo(lua_State *), 0x4AA730);
DEFINE_NAKED_JMP(int NSScriptDisappearNpc(lua_State *), 0x4A6950);
DEFINE_NAKED_JMP(int NSScriptLogout(lua_State *), 0x4AA660);
DEFINE_NAKED_JMP(int NSScriptGetServerMinute(lua_State *), 0x49F7B0);
DEFINE_NAKED_JMP(int NSScriptItemMining(lua_State *), 0x4A5170);
DEFINE_NAKED_JMP(int NSScriptTameMobSave(lua_State *), 0x4A0E50);
DEFINE_NAKED_JMP(int NSScriptGetRectInPcAvrLevel(lua_State *), 0x4A2EB0);
DEFINE_NAKED_JMP(int NSScriptHealRectInNpc(lua_State *), 0x4A4400);
DEFINE_NAKED_JMP(int NSScriptPetMessage(lua_State *), 0x4A64D0);
DEFINE_NAKED_JMP(int NSScriptItemAutoMining(lua_State *), 0x4A52A0);
DEFINE_NAKED_JMP(int NSScriptGetGuildPremiumItemDays(lua_State *), 0x4A86F0);
DEFINE_NAKED_JMP(int NSScriptSetShopRate(lua_State *), 0x49DCB0);
DEFINE_NAKED_JMP(int NSScriptWarpBind(lua_State *), 0x4A2160);
DEFINE_NAKED_JMP(int NSScriptPcTitleIsExist(lua_State *), 0x4AADE0);
DEFINE_NAKED_JMP(int NSScriptPcTitleGetCount(lua_State *), 0x4AAEA0);
DEFINE_NAKED_JMP(int NSScriptHealRectInPersonalSiegeWeapon(lua_State *), 0x4A3730);
DEFINE_NAKED_JMP(int NSScriptBroadcastBuff2(lua_State *), 0x4A9FA0);
DEFINE_NAKED_JMP(int NSScriptIsAggro(lua_State *), 0x49D8C0);
DEFINE_NAKED_JMP(int NSScriptPVPTournamentStart(lua_State *), 0x4A95F0);
DEFINE_NAKED_JMP(void NSScriptEnd(lua_State *), 0x49D460);
DEFINE_NAKED_JMP(int NSScriptAutoSkill(lua_State *), 0x4A8DE0);
DEFINE_NAKED_JMP(int NSScriptAddExpHitLastPc(lua_State *), 0x4AAB80);
DEFINE_NAKED_JMP(int NSScriptGetRectInPcCount2(lua_State *), 0x4A3010);
DEFINE_NAKED_JMP(int NSScriptGetRectInPcCount(lua_State *), 0x4A2840);
DEFINE_NAKED_JMP(int NSScriptWareHouseList(lua_State *), 0x4A88D0);
DEFINE_NAKED_JMP(int NSScriptPcTitleAdd(lua_State *), 0x4AACF0);
DEFINE_NAKED_JMP(int NSScriptSelfBuff(lua_State *), 0x4A9D90);
DEFINE_NAKED_JMP(int NSScriptReserveIsStart(lua_State *), 0x4AA910);
DEFINE_NAKED_JMP(int NSScriptGetLocalTime(lua_State *), 0x49F800);
DEFINE_NAKED_JMP(int NSScriptGetRectInNpcCount(lua_State *), 0x4A2B90);
DEFINE_NAKED_JMP(int NSScriptGetItemCount(lua_State *), 0x49E2B0);
DEFINE_NAKED_JMP(int NSScriptNpcQuestCheck(lua_State * _COMMA CNSNpc * _COMMA CNSPc *), 0x4AF970);
DEFINE_NAKED_JMP(int NSScriptGetRemainTime(lua_State *), 0x49E530);
DEFINE_NAKED_JMP(int NSScriptReserveWarp(lua_State *), 0x4AAAF0);
DEFINE_NAKED_JMP(int NSScriptWarpAndBind(lua_State *), 0x4A1470);
DEFINE_NAKED_JMP(int NSScriptPanic(lua_State *), 0x49D330);
DEFINE_NAKED_JMP(int NSScriptReserveAdd(lua_State *), 0x4AA970);
DEFINE_NAKED_JMP(int NSScriptGetRealmPoint(lua_State *), 0x49FDD0);
DEFINE_NAKED_JMP(int NSScriptNpcTalk(lua_State * _COMMA CNSNpc * _COMMA CNSPc * _COMMA char * _COMMA CPacket &), 0x4AB2E0);
DEFINE_NAKED_JMP(int NSScriptWareHouseSort(lua_State *), 0x4A8980);
DEFINE_NAKED_JMP(int NSScriptReserveDelete(lua_State *), 0x4AAA30);
DEFINE_NAKED_JMP(int NSScriptPSWFactory(lua_State *), 0x4A94A0);
DEFINE_NAKED_JMP(int NSScriptRVRStart(lua_State *), 0x4A9570);
DEFINE_NAKED_JMP(int NSScriptAwakeRectInNpc(lua_State *), 0x4A4090);
DEFINE_NAKED_JMP(int NSScriptIsPVEServerMode(lua_State *), 0x4A9890);
DEFINE_NAKED_JMP(int NSScriptGuildClose(lua_State *), 0x4A7830);
DEFINE_NAKED_JMP(int NSScriptWarpArea2(lua_State *), 0x4A1E20);
DEFINE_NAKED_JMP(int NSScriptGetRectInNpcHpPercent(lua_State *), 0x49D760);
DEFINE_NAKED_JMP(int NSScriptWarpArea(lua_State *), 0x4A1AB0);
DEFINE_NAKED_JMP(int NSScriptAutoRectInPartyJoin(lua_State *), 0x4A4810);
DEFINE_NAKED_JMP(int NSScriptGetGuildMemberRank(lua_State *), 0x4A7D30);
DEFINE_NAKED_JMP(int NSScriptIsRVRServerMode(lua_State *), 0x4A9850);
DEFINE_NAKED_JMP(int NSScriptAddItem(lua_State *), 0x4A0010);
DEFINE_NAKED_JMP(int NSScriptPartyMemberCount(lua_State *), 0x4A66F0);
DEFINE_NAKED_JMP(int NSScriptSetTargetNpc(lua_State *), 0x49DC00);
DEFINE_NAKED_JMP(int NSScriptAddRealmPoint(lua_State *), 0x49FE70);
DEFINE_NAKED_JMP(int NSScriptPrintGuildLog(lua_State *), 0x4A7E00);
DEFINE_NAKED_JMP(int NSScriptGiveRealmPoint(lua_State *), 0x49FF40);
DEFINE_NAKED_JMP(lua_State * NSScriptInit(unsigned short), 0x49D3A0);
DEFINE_NAKED_JMP(lua_State * NSScriptInit(), 0x49D350);
DEFINE_NAKED_JMP(int NSScriptAddSkill(lua_State *), 0x49E080);
DEFINE_NAKED_JMP(int NSScriptGetRectInNpcCount2(lua_State *), 0x4A3310);
DEFINE_NAKED_JMP(int NSScriptSkillReset(lua_State *), 0x4A8A90);
DEFINE_NAKED_JMP(int NSScriptSetClear(lua_State *), 0x49E990);
DEFINE_NAKED_JMP(int NSScriptHitRectInPcDebuff(lua_State *), 0x4A38C0);
DEFINE_NAKED_JMP(int NSScriptRideSiegeWeapon(lua_State *), 0x4A9010);
DEFINE_NAKED_JMP(int NSScriptIsRVRStart(lua_State *), 0x4A95B0);
DEFINE_NAKED_JMP(int NSScriptItemUnlock(lua_State *), 0x4A5430);
DEFINE_NAKED_JMP(int NSScriptNeoSlotCoinCount(lua_State *), 0x4AA430);
DEFINE_NAKED_JMP(int NSScriptBroadcastCenter(lua_State *), 0x4A6D50);
DEFINE_NAKED_JMP(int NSScriptGiveGuildPoint(lua_State *), 0x4A81A0);
DEFINE_NAKED_JMP(int NSScriptSkillChange(lua_State *), 0x4A8C60);
DEFINE_NAKED_JMP(int NSScriptCheckTimeOut(lua_State *), 0x49F500);
DEFINE_NAKED_JMP(int NSScriptUpgradePet(lua_State *), 0x4A6400);
DEFINE_NAKED_JMP(int NSScriptAddNeoSteam(lua_State *), 0x4A04A0);
DEFINE_NAKED_JMP(int NSScriptBroadcast(lua_State *), 0x4A6A30);
DEFINE_NAKED_JMP(void NSScriptPrintStackStatus(lua_State *), 0x49D480);
DEFINE_NAKED_JMP(int NSScriptSetTimeOut(lua_State *), 0x49F400);
DEFINE_NAKED_JMP(int NSScriptCheckItem(lua_State *), 0x49F860);
DEFINE_NAKED_JMP(int NSScriptNpcLoad(lua_State * _COMMA unsigned short), 0x49D650);
DEFINE_NAKED_JMP(int NSScriptChangeRace(lua_State *), 0x4A0B30);
DEFINE_NAKED_JMP(int NSScriptGetDescriptNpc(lua_State *), 0x4A5DF0);
DEFINE_NAKED_JMP(int NSScriptSetNextStep(lua_State *), 0x49E7C0);
DEFINE_NAKED_JMP(int NSScriptDeleteNpc(lua_State *), 0x4A67C0);
DEFINE_NAKED_JMP(int NSScriptRidePersonalSiegeWeapon(lua_State *), 0x4A9160);
DEFINE_NAKED_JMP(int NSScriptGetServerHour(lua_State *), 0x49F760);
DEFINE_NAKED_JMP(int NSScriptGetHpPercent(lua_State *), 0x49D6D0);
DEFINE_NAKED_JMP(int NSScriptGetStartSecond(lua_State *), 0x4AA2D0);
DEFINE_NAKED_JMP(int NSScriptWarpAndClarity(lua_State *), 0x4A2720);
DEFINE_NAKED_JMP(int NSScriptIsExistSkill(lua_State *), 0x49DFB0);
DEFINE_NAKED_JMP(int NSScriptIsMaxExp(lua_State *), 0x49EEB0);
DEFINE_NAKED_JMP(int NSScriptReserveEnd(lua_State *), 0x4AA8B0);
DEFINE_NAKED_JMP(int NSScriptGetDescriptItem(lua_State *), 0x4A5E70);
DEFINE_NAKED_JMP(int NSScriptGetGuildPoint(lua_State *), 0x4A7F80);
DEFINE_NAKED_JMP(int NSScriptChangePet(lua_State *), 0x4A6000);
DEFINE_NAKED_JMP(int NSScriptWarpParty(lua_State *), 0x4A1810);
DEFINE_NAKED_JMP(int NSScriptGiveGold(lua_State *), 0x49FAF0);
DEFINE_NAKED_JMP(int NSScriptBroadcastRealm(lua_State *), 0x4A7050);
DEFINE_NAKED_JMP(int NSScriptOfflineAutoSkillLoad(lua_State *), 0x4AA4C0);
DEFINE_NAKED_JMP(int NSScriptClearTimeOut(lua_State *), 0x49F6B0);
DEFINE_NAKED_JMP(int NSScriptIsPVPTournamentStart(lua_State *), 0x4A9650);
DEFINE_NAKED_JMP(int NSScriptGetPcZoneInfo(lua_State *), 0x4A99A0);
DEFINE_NAKED_JMP(int NSScriptLevelUp100(lua_State *), 0x49EDD0);
DEFINE_NAKED_JMP(int NSScriptGetRectInSiegeWeaponCount(lua_State *), 0x4A35D0);
DEFINE_NAKED_JMP(int NSScriptMaterialList(lua_State *), 0x4A0FB0);
DEFINE_NAKED_JMP(int NSScriptCheckNpc(lua_State *), 0x4A69B0);
DEFINE_NAKED_JMP(int NSScriptResolutionStart(lua_State *), 0x4A5A60);
DEFINE_NAKED_JMP(int NSScriptCallNpc(lua_State *), 0x49F300);
DEFINE_NAKED_JMP(int NSScriptGetRiderId(lua_State *), 0x4A8F70);
DEFINE_NAKED_JMP(int NSScriptAddGuildPoint(lua_State *), 0x4A8060);
DEFINE_NAKED_JMP(int NSScriptGetHitLastPcRealm(lua_State *), 0x4AAC60);
DEFINE_NAKED_JMP(int NSScriptItemGathering(lua_State *), 0x4A4E90);
DEFINE_NAKED_JMP(int NSScriptLevelUpRectInPc(lua_State *), 0x4A46F0);
DEFINE_NAKED_JMP(int NSScriptBroadcastNotify(lua_State *), 0x4A72C0);
DEFINE_NAKED_JMP(int NSScriptTameMobLoad(lua_State *), 0x4A0DC0);
DEFINE_NAKED_JMP(int NSScriptTransferMachine(lua_State *), 0x4A5EF0);
DEFINE_NAKED_JMP(int NSScriptHitBuff(lua_State *), 0x4A9A60);
DEFINE_NAKED_JMP(int NSScriptAddGold(lua_State *), 0x49FCD0);
DEFINE_NAKED_JMP(int NSScriptGetGuildRankMonthName(lua_State *), 0x4A83C0);
DEFINE_NAKED_JMP(int NSScriptGuildList(lua_State *), 0x4A76B0);
DEFINE_NAKED_JMP(int NSScriptSkillMake60(lua_State *), 0x49EE40);
DEFINE_NAKED_JMP(int NSScriptSkillPSWPartReset(lua_State *), 0x4A8D40);
DEFINE_NAKED_JMP(int NSScriptIsAdmin(lua_State *), 0x4A8ED0);
DEFINE_NAKED_JMP(int NSScriptAddQuest(lua_State *), 0x49EC30);
DEFINE_NAKED_JMP(int NSScriptGetGuildLevel(lua_State *), 0x4A78F0);
DEFINE_NAKED_JMP(int NSScriptWarpDelay(lua_State *), 0x4A2200);
DEFINE_NAKED_JMP(int NSScriptAddShopItem(lua_State *), 0x49D960);
DEFINE_NAKED_JMP(int NSScriptShopList(lua_State *), 0x49DDB0);
#endif

}




#endif