#ifndef NSHEADER_NS_SESSION_PC_PROCESS_H_
#define NSHEADER_NS_SESSION_PC_PROCESS_H_


namespace NSSessionPcProcess {

void SessionPcProcessInit();    PATCH_STATIC(void, SessionPcProcessInit, , 0x4C73A0);
void OnSCItemLoot(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemLoot, CNSSessionPc * _COMMA CPacket &, 0x4B8860);
int OnSCDebugOld(CNSSessionPc *, CPacket &, char *);    PATCH_STATIC(int, OnSCDebugOld, CNSSessionPc * _COMMA CPacket & _COMMA char *, 0x4BDBF0);
void OnSCWareHouseInGold(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCWareHouseInGold, CNSSessionPc * _COMMA CPacket &, 0x4C5B60);
void OnSCPcBindPos(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcBindPos, CNSSessionPc * _COMMA CPacket &, 0x4B6580);
void OnSCQuestGiveUp(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCQuestGiveUp, CNSSessionPc * _COMMA CPacket &, 0x4BAF80);
void OnSCGuildChangeComment(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildChangeComment, CNSSessionPc * _COMMA CPacket &, 0x4C5060);
void OnSCPcShopSell(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcShopSell, CNSSessionPc * _COMMA CPacket &, 0x4C4760);
void OnSCAliasList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAliasList, CNSSessionPc * _COMMA CPacket &, 0x4B4D70);
void OnSCPremiumShopList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPremiumShopList, CNSSessionPc * _COMMA CPacket &, 0x4C3FB0);
void OnSCPremiumShopSell(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPremiumShopSell, CNSSessionPc * _COMMA CPacket &, 0x4C4080);
void OnSCGuildQuit(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildQuit, CNSSessionPc * _COMMA CPacket &, 0x4C5800);
void OnSCItemUse(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemUse, CNSSessionPc * _COMMA CPacket &, 0x4B8C40);
void OnSCItemMove(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemMove, CNSSessionPc * _COMMA CPacket &, 0x4B8AD0);
void OnSCGuildJoinReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildJoinReq, CNSSessionPc * _COMMA CPacket &, 0x4C52D0);
void OnSCGuildKick(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildKick, CNSSessionPc * _COMMA CPacket &, 0x4C5920);
void OnSCShopItemCost(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCShopItemCost, CNSSessionPc * _COMMA CPacket &, 0x4B95F0);
void OnSCSkillTest(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCSkillTest, CNSSessionPc * _COMMA CPacket &, 0x4C66F0);
void OnSCItemParamDescription(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemParamDescription, CNSSessionPc * _COMMA CPacket &, 0x4B8490);
void OnSCGuildOpen(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildOpen, CNSSessionPc * _COMMA CPacket &, 0x4C4AA0);
void OnSCProductMake(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCProductMake, CNSSessionPc * _COMMA CPacket &, 0x4BB200);
void OnSSNpcTalk(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSNpcTalk, CNSSessionPc * _COMMA CPacket &, 0x4C6C00);
void OnSCNpcTalk(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCNpcTalk, CNSSessionPc * _COMMA CPacket &, 0x4BA500);
void OnSCRebirth(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCRebirth, CNSSessionPc * _COMMA CPacket &, 0x4BCD20);
void OnSCAutoRunStart(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAutoRunStart, CNSSessionPc * _COMMA CPacket &, 0x4B6640);
void OnSSGuildClose(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGuildClose, CNSSessionPc * _COMMA CPacket &, 0x4C6920);
void OnSCGuildClose(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildClose, CNSSessionPc * _COMMA CPacket &, 0x4C4BB0);
void OnSCItemSort(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemSort, CNSSessionPc * _COMMA CPacket &, 0x4C38F0);
void OnSCAuctionList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAuctionList, CNSSessionPc * _COMMA CPacket &, 0x4C6000);
void OnSCAuctionSell(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAuctionSell, CNSSessionPc * _COMMA CPacket &, 0x4C6260);
void OnSCBuffTest(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCBuffTest, CNSSessionPc * _COMMA CPacket &, 0x4C6750);
void OnSCAliasDelete(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAliasDelete, CNSSessionPc * _COMMA CPacket &, 0x4B5130);
void OnSCAliasSelect(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAliasSelect, CNSSessionPc * _COMMA CPacket &, 0x4B4DE0);
void OnSCServerDisconnect(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCServerDisconnect, CNSSessionPc * _COMMA CPacket &, 0x4C2DD0);
void OnSCPcChat(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcChat, CNSSessionPc * _COMMA CPacket &, 0x4B6EC0);
void OnSCShopItemList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCShopItemList, CNSSessionPc * _COMMA CPacket &, 0x4B9300);
void OnSCPartyCreate(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyCreate, CNSSessionPc * _COMMA CPacket &, 0x4BB900);
void OnSCTeleportCast(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTeleportCast, CNSSessionPc * _COMMA CPacket &, 0x4C3AE0);
void OnSCGuildChangeName(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildChangeName, CNSSessionPc * _COMMA CPacket &, 0x4C4EC0);
void OnSCPartyInviteReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyInviteReq, CNSSessionPc * _COMMA CPacket &, 0x4BCA00);
void OnSCTimeSync(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTimeSync, CNSSessionPc * _COMMA CPacket &, 0x4B67B0);
void OnSCGuildList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildList, CNSSessionPc * _COMMA CPacket &, 0x4C4CC0);
void OnSSFriendAdd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSFriendAdd, CNSSessionPc * _COMMA CPacket &, 0x4C7280);
void OnSCFriendAdd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCFriendAdd, CNSSessionPc * _COMMA CPacket &, 0x4C3BD0);
void OnSCSkillCast(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCSkillCast, CNSSessionPc * _COMMA CPacket &, 0x4BA970);
void OnSCPcShopClose(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcShopClose, CNSSessionPc * _COMMA CPacket &, 0x4C4470);
void OnSCItemList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemList, CNSSessionPc * _COMMA CPacket &, 0x4C38D0);
void OnSCPcShopOpen(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcShopOpen, CNSSessionPc * _COMMA CPacket &, 0x4C41D0);
void OnSCGameLeave(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGameLeave, CNSSessionPc * _COMMA CPacket &, 0x4B5570);
void OnSSGameLeave(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGameLeave, CNSSessionPc * _COMMA CPacket &, 0x4B5680);
void OnSCProductDescription(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCProductDescription, CNSSessionPc * _COMMA CPacket &, 0x4BB1D0);
void OnSSChatBroadcast(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSChatBroadcast, CNSSessionPc * _COMMA CPacket &, 0x4C7100);
void OnSCPcEquipInfo(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcEquipInfo, CNSSessionPc * _COMMA CPacket &, 0x4BCDE0);
void OnSCGuildInfo(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildInfo, CNSSessionPc * _COMMA CPacket &, 0x4C4D50);
void OnSSGuildInfo(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGuildInfo, CNSSessionPc * _COMMA CPacket &, 0x4C6820);
void OnSCPetFood(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPetFood, CNSSessionPc * _COMMA CPacket &, 0x4BCF60);
void OnSCGuildChangeMaster(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildChangeMaster, CNSSessionPc * _COMMA CPacket &, 0x4C4D90);
void OnSCRecombination(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCRecombination, CNSSessionPc * _COMMA CPacket &, 0x4BB640);
void OnSCEcho(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCEcho, CNSSessionPc * _COMMA CPacket &, 0x4C2B10);
void OnSCPartyJoin(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyJoin, CNSSessionPc * _COMMA CPacket &, 0x4BBA90);
void OnSCTitleDescription(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTitleDescription, CNSSessionPc * _COMMA CPacket &, 0x4C6540);
void OnSCItemDescription(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemDescription, CNSSessionPc * _COMMA CPacket &, 0x4B8220);
void OnSCPcShopList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcShopList, CNSSessionPc * _COMMA CPacket &, 0x4C4590);
void OnSCSkillDescription(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCSkillDescription, CNSSessionPc * _COMMA CPacket &, 0x4BAC50);
void OnSCWareHouseInItem(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCWareHouseInItem, CNSSessionPc * _COMMA CPacket &, 0x4C5A70);
void OnSCTeleportDelete(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTeleportDelete, CNSSessionPc * _COMMA CPacket &, 0x4C3A20);
void OnSSGuildMemberJoin(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGuildMemberJoin, CNSSessionPc * _COMMA CPacket &, 0x4C6960);
void OnSCGameLeave2(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGameLeave2, CNSSessionPc * _COMMA CPacket &, 0x4B5810);
void OnSSChatChannelChat(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSChatChannelChat, CNSSessionPc * _COMMA CPacket &, 0x4C6EB0);
void OnSCPartyPasswordChange(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyPasswordChange, CNSSessionPc * _COMMA CPacket &, 0x4BC200);
void OnSCStatus(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCStatus, CNSSessionPc * _COMMA CPacket &, 0x4C38B0);
void OnSSTest(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSTest, CNSSessionPc * _COMMA CPacket &, 0x4C67D0);
void OnSCPremiumSkillLevelUp(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPremiumSkillLevelUp, CNSSessionPc * _COMMA CPacket &, 0x4BAEB0);
void OnSCAuctionDelete(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAuctionDelete, CNSSessionPc * _COMMA CPacket &, 0x4C6340);
void OnSCTitleSelect(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTitleSelect, CNSSessionPc * _COMMA CPacket &, 0x4C6420);
void OnSCItemCombine(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemCombine, CNSSessionPc * _COMMA CPacket &, 0x4B8EA0);
void OnSCSkillStudy(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCSkillStudy, CNSSessionPc * _COMMA CPacket &, 0x4BAB90);
void OnSCWareHouseOutGold(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCWareHouseOutGold, CNSSessionPc * _COMMA CPacket &, 0x4C5E30);
void OnSCWareHouseOutConfirm(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCWareHouseOutConfirm, CNSSessionPc * _COMMA CPacket &, 0x4C5F00);
void OnSCUsePhoenix(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCUsePhoenix, CNSSessionPc * _COMMA CPacket &, 0x4BCEF0);
void OnSCPcAssistReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcAssistReq, CNSSessionPc * _COMMA CPacket &, 0x4B6D80);
void OnSCExchangeItem(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCExchangeItem, CNSSessionPc * _COMMA CPacket &, 0x4B9D10);
void OnSCPetInfoReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPetInfoReq, CNSSessionPc * _COMMA CPacket &, 0x4B5D60);
void OnSCPcTraceLootReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcTraceLootReq, CNSSessionPc * _COMMA CPacket &, 0x4B6D20);
void OnSCAuctionAdd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAuctionAdd, CNSSessionPc * _COMMA CPacket &, 0x4C6150);
void OnSCPcAttackCancel(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcAttackCancel, CNSSessionPc * _COMMA CPacket &, 0x4B6B60);
void OnSCCashInfo(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCCashInfo, CNSSessionPc * _COMMA CPacket &, 0x4C4150);
void OnSSGuildMemberUpdate(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGuildMemberUpdate, CNSSessionPc * _COMMA CPacket &, 0x4C69E0);
void OnSCGuildJoin(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildJoin, CNSSessionPc * _COMMA CPacket &, 0x4C5680);
void OnSCProductList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCProductList, CNSSessionPc * _COMMA CPacket &, 0x4BB1B0);
void OnSCExchangeConfirm(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCExchangeConfirm, CNSSessionPc * _COMMA CPacket &, 0x4BA050);
void OnSCServerNotice(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCServerNotice, CNSSessionPc * _COMMA CPacket &, 0x4C2F90);
void OnSCQuickBarSave(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCQuickBarSave, CNSSessionPc * _COMMA CPacket &, 0x4BB120);
void OnSCPartyLootChange(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyLootChange, CNSSessionPc * _COMMA CPacket &, 0x4BC370);
void OnSCWareHouseInConfirm(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCWareHouseInConfirm, CNSSessionPc * _COMMA CPacket &, 0x4C5C30);
void OnSSGMemoWrite(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGMemoWrite, CNSSessionPc * _COMMA CPacket &, 0x4C6AF0);
void OnSCEventEnd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCEventEnd, CNSSessionPc * _COMMA CPacket &, 0x4BCD70);
void OnSCPartyNameChange(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyNameChange, CNSSessionPc * _COMMA CPacket &, 0x4BBFF0);
void OnSCItemInfo(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemInfo, CNSSessionPc * _COMMA CPacket &, 0x4B9210);
void OnSCPcAttackReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcAttackReq, CNSSessionPc * _COMMA CPacket &, 0x4B6820);
void OnSCQuestSummary(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCQuestSummary, CNSSessionPc * _COMMA CPacket &, 0x4BB040);
void OnSCServerCheck(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCServerCheck, CNSSessionPc * _COMMA CPacket &, 0x4C2B90);
void OnSCSessionPcMove(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCSessionPcMove, CNSSessionPc * _COMMA CPacket &, 0x4B5B60);
void OnSCDebug(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCDebug, CNSSessionPc * _COMMA CPacket &, 0x4BD020);
void OnSCItemEquipment(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemEquipment, CNSSessionPc * _COMMA CPacket &, 0x4B8970);
void OnSCGameLoginReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGameLoginReq, CNSSessionPc * _COMMA CPacket &, 0x4B4AF0);
void OnSCWareHouseOutItem(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCWareHouseOutItem, CNSSessionPc * _COMMA CPacket &, 0x4C5D40);
void OnSCResolution(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCResolution, CNSSessionPc * _COMMA CPacket &, 0x4BB410);
void OnSSGuildPointAdd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGuildPointAdd, CNSSessionPc * _COMMA CPacket &, 0x4C71E0);
void OnSCGuildChangeRank(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGuildChangeRank, CNSSessionPc * _COMMA CPacket &, 0x4C5190);
void OnSCIdle(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCIdle, CNSSessionPc * _COMMA CPacket &, 0x4C7390);
void OnSCTameMobInfoReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTameMobInfoReq, CNSSessionPc * _COMMA CPacket &, 0x4B5CB0);
void OnSCItemUpgrade(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemUpgrade, CNSSessionPc * _COMMA CPacket &, 0x4B90D0);
void OnSCPCJump(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPCJump, CNSSessionPc * _COMMA CPacket &, 0x4B6710);
void OnSSGuildMemberQuit(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSGuildMemberQuit, CNSSessionPc * _COMMA CPacket &, 0x4C6A70);
void OnSCBuffDescription(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCBuffDescription, CNSSessionPc * _COMMA CPacket &, 0x4BAD70);
void OnSCPcMoveReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcMoveReq, CNSSessionPc * _COMMA CPacket &, 0x4B5FB0);
void OnSCTeleportList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTeleportList, CNSSessionPc * _COMMA CPacket &, 0x4C3920);
void OnSCGameLogin2Req(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGameLogin2Req, CNSSessionPc * _COMMA CPacket &, 0x4B5200);
void OnSCPartyKick(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyKick, CNSSessionPc * _COMMA CPacket &, 0x4BBE30);
void OnSCItemDivide(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemDivide, CNSSessionPc * _COMMA CPacket &, 0x4B8FC0);
void OnSCPcResistReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcResistReq, CNSSessionPc * _COMMA CPacket &, 0x4B6BB0);
void OnSCShopItemTrade(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCShopItemTrade, CNSSessionPc * _COMMA CPacket &, 0x4B93F0);
void OnSCSkillCancel(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCSkillCancel, CNSSessionPc * _COMMA CPacket &, 0x4BAB70);
void OnSCUseSkillReset(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCUseSkillReset, CNSSessionPc * _COMMA CPacket &, 0x4BCF20);
void OnSCFriendList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCFriendList, CNSSessionPc * _COMMA CPacket &, 0x4C3BB0);
void OnSCCharInfoReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCCharInfoReq, CNSSessionPc * _COMMA CPacket &, 0x4B5BA0);
void OnSCExchangeReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCExchangeReq, CNSSessionPc * _COMMA CPacket &, 0x4B9770);
void OnSCWareHouseList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCWareHouseList, CNSSessionPc * _COMMA CPacket &, 0x4C5A40);
void OnSCItemDelete(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCItemDelete, CNSSessionPc * _COMMA CPacket &, 0x4B8DD0);
void OnSSFriendDelete(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSSFriendDelete, CNSSessionPc * _COMMA CPacket &, 0x4C7310);
void OnSCFriendDelete(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCFriendDelete, CNSSessionPc * _COMMA CPacket &, 0x4C3C80);
void OnSCDropItemList(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCDropItemList, CNSSessionPc * _COMMA CPacket &, 0x4B8710);
void OnSCAutoRunEnd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAutoRunEnd, CNSSessionPc * _COMMA CPacket &, 0x4B66F0);
void OnSCTameMobNameChange(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTameMobNameChange, CNSSessionPc * _COMMA CPacket &, 0x4B5D80);
void OnSCRealmMapInfo(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCRealmMapInfo, CNSSessionPc * _COMMA CPacket &, 0x4C6680);
void OnSCPartyQuit(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyQuit, CNSSessionPc * _COMMA CPacket &, 0x4BBD20);
void OnSCFriendAddReq(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCFriendAddReq, CNSSessionPc * _COMMA CPacket &, 0x4C3D30);
void OnSCPartyInvite(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPartyInvite, CNSSessionPc * _COMMA CPacket &, 0x4BC5A0);
void OnSCPcShopBuy(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCPcShopBuy, CNSSessionPc * _COMMA CPacket &, 0x4C4900);
void OnSCGameEnter(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCGameEnter, CNSSessionPc * _COMMA CPacket &, 0x4B5520);
void OnSCAliasCreate(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCAliasCreate, CNSSessionPc * _COMMA CPacket &, 0x4B5030);
void OnSCExchangeCancel(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCExchangeCancel, CNSSessionPc * _COMMA CPacket &, 0x4BA410);
void OnSCCmdRename(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCCmdRename, CNSSessionPc * _COMMA CPacket &, 0x4C6620);
void OnSCTeleportAdd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnSCTeleportAdd, CNSSessionPc * _COMMA CPacket &, 0x4C3950);
void OnISSkillUse(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISSkillUse, CNSSessionPc * _COMMA CPacket &, 0x4C3330);
void OnISLogWrite(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISLogWrite, CNSSessionPc * _COMMA CPacket &, 0x4C3710);
void OnISGMemoWrite(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISGMemoWrite, CNSSessionPc * _COMMA CPacket &, 0x4C34B0);
void OnISCheckDoubleConnect(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISCheckDoubleConnect, CNSSessionPc * _COMMA CPacket &, 0x4C36D0);
void OnISQuestMobCheck(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISQuestMobCheck, CNSSessionPc * _COMMA CPacket &, 0x4C3260);
void OnISEventItemAdd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISEventItemAdd, CNSSessionPc * _COMMA CPacket &, 0x4C3850);
void OnISPVPItemAdd(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISPVPItemAdd, CNSSessionPc * _COMMA CPacket &, 0x4C32A0);
void OnISMemoWrite(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISMemoWrite, CNSSessionPc * _COMMA CPacket &, 0x4C33C0);
void OnISItemLootAll(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISItemLootAll, CNSSessionPc * _COMMA CPacket &, 0x4C31F0);
void OnISTameMobSave(CNSSessionPc *, CPacket &);    PATCH_STATIC(void, OnISTameMobSave, CNSSessionPc * _COMMA CPacket &, 0x4C36B0);



#ifdef DEFINE_NS_CPP
//DEFINE_NAKED_JMP(void SessionPcProcessInit(), 0x4C73A0);
DEFINE_NAKED_JMP(int OnSCDebugOld(CNSSessionPc * _COMMA CPacket & _COMMA char *), 0x4BDBF0);
DEFINE_NAKED_JMP(void OnSCItemLoot(CNSSessionPc * _COMMA CPacket &), 0x4B8860);
DEFINE_NAKED_JMP(void OnSCWareHouseInGold(CNSSessionPc * _COMMA CPacket &), 0x4C5B60);
DEFINE_NAKED_JMP(void OnSCPcBindPos(CNSSessionPc * _COMMA CPacket &), 0x4B6580);
DEFINE_NAKED_JMP(void OnSCQuestGiveUp(CNSSessionPc * _COMMA CPacket &), 0x4BAF80);
DEFINE_NAKED_JMP(void OnSCGuildChangeComment(CNSSessionPc * _COMMA CPacket &), 0x4C5060);
DEFINE_NAKED_JMP(void OnSCPcShopSell(CNSSessionPc * _COMMA CPacket &), 0x4C4760);
DEFINE_NAKED_JMP(void OnSCAliasList(CNSSessionPc * _COMMA CPacket &), 0x4B4D70);
DEFINE_NAKED_JMP(void OnSCPremiumShopList(CNSSessionPc * _COMMA CPacket &), 0x4C3FB0);
DEFINE_NAKED_JMP(void OnSCPremiumShopSell(CNSSessionPc * _COMMA CPacket &), 0x4C4080);
DEFINE_NAKED_JMP(void OnSCGuildQuit(CNSSessionPc * _COMMA CPacket &), 0x4C5800);
DEFINE_NAKED_JMP(void OnSCItemUse(CNSSessionPc * _COMMA CPacket &), 0x4B8C40);
DEFINE_NAKED_JMP(void OnSCItemMove(CNSSessionPc * _COMMA CPacket &), 0x4B8AD0);
DEFINE_NAKED_JMP(void OnSCGuildJoinReq(CNSSessionPc * _COMMA CPacket &), 0x4C52D0);
DEFINE_NAKED_JMP(void OnSCGuildKick(CNSSessionPc * _COMMA CPacket &), 0x4C5920);
DEFINE_NAKED_JMP(void OnSCShopItemCost(CNSSessionPc * _COMMA CPacket &), 0x4B95F0);
DEFINE_NAKED_JMP(void OnSCSkillTest(CNSSessionPc * _COMMA CPacket &), 0x4C66F0);
DEFINE_NAKED_JMP(void OnSCItemParamDescription(CNSSessionPc * _COMMA CPacket &), 0x4B8490);
DEFINE_NAKED_JMP(void OnSCGuildOpen(CNSSessionPc * _COMMA CPacket &), 0x4C4AA0);
DEFINE_NAKED_JMP(void OnSCProductMake(CNSSessionPc * _COMMA CPacket &), 0x4BB200);
DEFINE_NAKED_JMP(void OnSSNpcTalk(CNSSessionPc * _COMMA CPacket &), 0x4C6C00);
DEFINE_NAKED_JMP(void OnSCNpcTalk(CNSSessionPc * _COMMA CPacket &), 0x4BA500);
DEFINE_NAKED_JMP(void OnSCRebirth(CNSSessionPc * _COMMA CPacket &), 0x4BCD20);
DEFINE_NAKED_JMP(void OnSCAutoRunStart(CNSSessionPc * _COMMA CPacket &), 0x4B6640);
DEFINE_NAKED_JMP(void OnSSGuildClose(CNSSessionPc * _COMMA CPacket &), 0x4C6920);
DEFINE_NAKED_JMP(void OnSCGuildClose(CNSSessionPc * _COMMA CPacket &), 0x4C4BB0);
DEFINE_NAKED_JMP(void OnSCItemSort(CNSSessionPc * _COMMA CPacket &), 0x4C38F0);
DEFINE_NAKED_JMP(void OnSCAuctionList(CNSSessionPc * _COMMA CPacket &), 0x4C6000);
DEFINE_NAKED_JMP(void OnSCAuctionSell(CNSSessionPc * _COMMA CPacket &), 0x4C6260);
DEFINE_NAKED_JMP(void OnSCBuffTest(CNSSessionPc * _COMMA CPacket &), 0x4C6750);
DEFINE_NAKED_JMP(void OnSCAliasDelete(CNSSessionPc * _COMMA CPacket &), 0x4B5130);
DEFINE_NAKED_JMP(void OnSCAliasSelect(CNSSessionPc * _COMMA CPacket &), 0x4B4DE0);
DEFINE_NAKED_JMP(void OnSCServerDisconnect(CNSSessionPc * _COMMA CPacket &), 0x4C2DD0);
DEFINE_NAKED_JMP(void OnSCPcChat(CNSSessionPc * _COMMA CPacket &), 0x4B6EC0);
DEFINE_NAKED_JMP(void OnSCShopItemList(CNSSessionPc * _COMMA CPacket &), 0x4B9300);
DEFINE_NAKED_JMP(void OnSCPartyCreate(CNSSessionPc * _COMMA CPacket &), 0x4BB900);
DEFINE_NAKED_JMP(void OnSCTeleportCast(CNSSessionPc * _COMMA CPacket &), 0x4C3AE0);
DEFINE_NAKED_JMP(void OnSCGuildChangeName(CNSSessionPc * _COMMA CPacket &), 0x4C4EC0);
DEFINE_NAKED_JMP(void OnSCPartyInviteReq(CNSSessionPc * _COMMA CPacket &), 0x4BCA00);
DEFINE_NAKED_JMP(void OnSCTimeSync(CNSSessionPc * _COMMA CPacket &), 0x4B67B0);
DEFINE_NAKED_JMP(void OnSCGuildList(CNSSessionPc * _COMMA CPacket &), 0x4C4CC0);
DEFINE_NAKED_JMP(void OnSSFriendAdd(CNSSessionPc * _COMMA CPacket &), 0x4C7280);
DEFINE_NAKED_JMP(void OnSCFriendAdd(CNSSessionPc * _COMMA CPacket &), 0x4C3BD0);
DEFINE_NAKED_JMP(void OnSCSkillCast(CNSSessionPc * _COMMA CPacket &), 0x4BA970);
DEFINE_NAKED_JMP(void OnSCPcShopClose(CNSSessionPc * _COMMA CPacket &), 0x4C4470);
DEFINE_NAKED_JMP(void OnSCItemList(CNSSessionPc * _COMMA CPacket &), 0x4C38D0);
DEFINE_NAKED_JMP(void OnSCPcShopOpen(CNSSessionPc * _COMMA CPacket &), 0x4C41D0);
DEFINE_NAKED_JMP(void OnSCGameLeave(CNSSessionPc * _COMMA CPacket &), 0x4B5570);
DEFINE_NAKED_JMP(void OnSSGameLeave(CNSSessionPc * _COMMA CPacket &), 0x4B5680);
DEFINE_NAKED_JMP(void OnSCProductDescription(CNSSessionPc * _COMMA CPacket &), 0x4BB1D0);
DEFINE_NAKED_JMP(void OnSSChatBroadcast(CNSSessionPc * _COMMA CPacket &), 0x4C7100);
DEFINE_NAKED_JMP(void OnSCPcEquipInfo(CNSSessionPc * _COMMA CPacket &), 0x4BCDE0);
DEFINE_NAKED_JMP(void OnSCGuildInfo(CNSSessionPc * _COMMA CPacket &), 0x4C4D50);
DEFINE_NAKED_JMP(void OnSSGuildInfo(CNSSessionPc * _COMMA CPacket &), 0x4C6820);
DEFINE_NAKED_JMP(void OnSCPetFood(CNSSessionPc * _COMMA CPacket &), 0x4BCF60);
DEFINE_NAKED_JMP(void OnSCGuildChangeMaster(CNSSessionPc * _COMMA CPacket &), 0x4C4D90);
DEFINE_NAKED_JMP(void OnSCRecombination(CNSSessionPc * _COMMA CPacket &), 0x4BB640);
DEFINE_NAKED_JMP(void OnSCEcho(CNSSessionPc * _COMMA CPacket &), 0x4C2B10);
DEFINE_NAKED_JMP(void OnSCPartyJoin(CNSSessionPc * _COMMA CPacket &), 0x4BBA90);
DEFINE_NAKED_JMP(void OnSCTitleDescription(CNSSessionPc * _COMMA CPacket &), 0x4C6540);
DEFINE_NAKED_JMP(void OnSCItemDescription(CNSSessionPc * _COMMA CPacket &), 0x4B8220);
DEFINE_NAKED_JMP(void OnSCPcShopList(CNSSessionPc * _COMMA CPacket &), 0x4C4590);
DEFINE_NAKED_JMP(void OnSCSkillDescription(CNSSessionPc * _COMMA CPacket &), 0x4BAC50);
DEFINE_NAKED_JMP(void OnSCWareHouseInItem(CNSSessionPc * _COMMA CPacket &), 0x4C5A70);
DEFINE_NAKED_JMP(void OnSCTeleportDelete(CNSSessionPc * _COMMA CPacket &), 0x4C3A20);
DEFINE_NAKED_JMP(void OnSSGuildMemberJoin(CNSSessionPc * _COMMA CPacket &), 0x4C6960);
DEFINE_NAKED_JMP(void OnSCGameLeave2(CNSSessionPc * _COMMA CPacket &), 0x4B5810);
DEFINE_NAKED_JMP(void OnSSChatChannelChat(CNSSessionPc * _COMMA CPacket &), 0x4C6EB0);
DEFINE_NAKED_JMP(void OnSCPartyPasswordChange(CNSSessionPc * _COMMA CPacket &), 0x4BC200);
DEFINE_NAKED_JMP(void OnSCStatus(CNSSessionPc * _COMMA CPacket &), 0x4C38B0);
DEFINE_NAKED_JMP(void OnSSTest(CNSSessionPc * _COMMA CPacket &), 0x4C67D0);
DEFINE_NAKED_JMP(void OnSCPremiumSkillLevelUp(CNSSessionPc * _COMMA CPacket &), 0x4BAEB0);
DEFINE_NAKED_JMP(void OnSCAuctionDelete(CNSSessionPc * _COMMA CPacket &), 0x4C6340);
DEFINE_NAKED_JMP(void OnSCTitleSelect(CNSSessionPc * _COMMA CPacket &), 0x4C6420);
DEFINE_NAKED_JMP(void OnSCItemCombine(CNSSessionPc * _COMMA CPacket &), 0x4B8EA0);
DEFINE_NAKED_JMP(void OnSCSkillStudy(CNSSessionPc * _COMMA CPacket &), 0x4BAB90);
DEFINE_NAKED_JMP(void OnSCWareHouseOutGold(CNSSessionPc * _COMMA CPacket &), 0x4C5E30);
DEFINE_NAKED_JMP(void OnSCWareHouseOutConfirm(CNSSessionPc * _COMMA CPacket &), 0x4C5F00);
DEFINE_NAKED_JMP(void OnSCUsePhoenix(CNSSessionPc * _COMMA CPacket &), 0x4BCEF0);
DEFINE_NAKED_JMP(void OnSCPcAssistReq(CNSSessionPc * _COMMA CPacket &), 0x4B6D80);
DEFINE_NAKED_JMP(void OnSCExchangeItem(CNSSessionPc * _COMMA CPacket &), 0x4B9D10);
DEFINE_NAKED_JMP(void OnSCPetInfoReq(CNSSessionPc * _COMMA CPacket &), 0x4B5D60);
DEFINE_NAKED_JMP(void OnSCPcTraceLootReq(CNSSessionPc * _COMMA CPacket &), 0x4B6D20);
DEFINE_NAKED_JMP(void OnSCAuctionAdd(CNSSessionPc * _COMMA CPacket &), 0x4C6150);
DEFINE_NAKED_JMP(void OnSCPcAttackCancel(CNSSessionPc * _COMMA CPacket &), 0x4B6B60);
DEFINE_NAKED_JMP(void OnSCCashInfo(CNSSessionPc * _COMMA CPacket &), 0x4C4150);
DEFINE_NAKED_JMP(void OnSSGuildMemberUpdate(CNSSessionPc * _COMMA CPacket &), 0x4C69E0);
DEFINE_NAKED_JMP(void OnSCGuildJoin(CNSSessionPc * _COMMA CPacket &), 0x4C5680);
DEFINE_NAKED_JMP(void OnSCProductList(CNSSessionPc * _COMMA CPacket &), 0x4BB1B0);
DEFINE_NAKED_JMP(void OnSCExchangeConfirm(CNSSessionPc * _COMMA CPacket &), 0x4BA050);
DEFINE_NAKED_JMP(void OnSCServerNotice(CNSSessionPc * _COMMA CPacket &), 0x4C2F90);
DEFINE_NAKED_JMP(void OnSCQuickBarSave(CNSSessionPc * _COMMA CPacket &), 0x4BB120);
DEFINE_NAKED_JMP(void OnSCPartyLootChange(CNSSessionPc * _COMMA CPacket &), 0x4BC370);
DEFINE_NAKED_JMP(void OnSCWareHouseInConfirm(CNSSessionPc * _COMMA CPacket &), 0x4C5C30);
DEFINE_NAKED_JMP(void OnSSGMemoWrite(CNSSessionPc * _COMMA CPacket &), 0x4C6AF0);
DEFINE_NAKED_JMP(void OnSCEventEnd(CNSSessionPc * _COMMA CPacket &), 0x4BCD70);
DEFINE_NAKED_JMP(void OnSCPartyNameChange(CNSSessionPc * _COMMA CPacket &), 0x4BBFF0);
DEFINE_NAKED_JMP(void OnSCItemInfo(CNSSessionPc * _COMMA CPacket &), 0x4B9210);
DEFINE_NAKED_JMP(void OnSCPcAttackReq(CNSSessionPc * _COMMA CPacket &), 0x4B6820);
DEFINE_NAKED_JMP(void OnSCQuestSummary(CNSSessionPc * _COMMA CPacket &), 0x4BB040);
DEFINE_NAKED_JMP(void OnSCServerCheck(CNSSessionPc * _COMMA CPacket &), 0x4C2B90);
DEFINE_NAKED_JMP(void OnSCSessionPcMove(CNSSessionPc * _COMMA CPacket &), 0x4B5B60);
DEFINE_NAKED_JMP(void OnSCDebug(CNSSessionPc * _COMMA CPacket &), 0x4BD020);
DEFINE_NAKED_JMP(void OnSCItemEquipment(CNSSessionPc * _COMMA CPacket &), 0x4B8970);
DEFINE_NAKED_JMP(void OnSCGameLoginReq(CNSSessionPc * _COMMA CPacket &), 0x4B4AF0);
DEFINE_NAKED_JMP(void OnSCWareHouseOutItem(CNSSessionPc * _COMMA CPacket &), 0x4C5D40);
DEFINE_NAKED_JMP(void OnSCResolution(CNSSessionPc * _COMMA CPacket &), 0x4BB410);
DEFINE_NAKED_JMP(void OnSSGuildPointAdd(CNSSessionPc * _COMMA CPacket &), 0x4C71E0);
DEFINE_NAKED_JMP(void OnSCGuildChangeRank(CNSSessionPc * _COMMA CPacket &), 0x4C5190);
DEFINE_NAKED_JMP(void OnSCIdle(CNSSessionPc * _COMMA CPacket &), 0x4C7390);
DEFINE_NAKED_JMP(void OnSCTameMobInfoReq(CNSSessionPc * _COMMA CPacket &), 0x4B5CB0);
DEFINE_NAKED_JMP(void OnSCItemUpgrade(CNSSessionPc * _COMMA CPacket &), 0x4B90D0);
DEFINE_NAKED_JMP(void OnSCPCJump(CNSSessionPc * _COMMA CPacket &), 0x4B6710);
DEFINE_NAKED_JMP(void OnSSGuildMemberQuit(CNSSessionPc * _COMMA CPacket &), 0x4C6A70);
DEFINE_NAKED_JMP(void OnSCBuffDescription(CNSSessionPc * _COMMA CPacket &), 0x4BAD70);
DEFINE_NAKED_JMP(void OnSCPcMoveReq(CNSSessionPc * _COMMA CPacket &), 0x4B5FB0);
DEFINE_NAKED_JMP(void OnSCTeleportList(CNSSessionPc * _COMMA CPacket &), 0x4C3920);
DEFINE_NAKED_JMP(void OnSCGameLogin2Req(CNSSessionPc * _COMMA CPacket &), 0x4B5200);
DEFINE_NAKED_JMP(void OnSCPartyKick(CNSSessionPc * _COMMA CPacket &), 0x4BBE30);
DEFINE_NAKED_JMP(void OnSCItemDivide(CNSSessionPc * _COMMA CPacket &), 0x4B8FC0);
DEFINE_NAKED_JMP(void OnSCPcResistReq(CNSSessionPc * _COMMA CPacket &), 0x4B6BB0);
DEFINE_NAKED_JMP(void OnSCShopItemTrade(CNSSessionPc * _COMMA CPacket &), 0x4B93F0);
DEFINE_NAKED_JMP(void OnSCSkillCancel(CNSSessionPc * _COMMA CPacket &), 0x4BAB70);
DEFINE_NAKED_JMP(void OnSCUseSkillReset(CNSSessionPc * _COMMA CPacket &), 0x4BCF20);
DEFINE_NAKED_JMP(void OnSCFriendList(CNSSessionPc * _COMMA CPacket &), 0x4C3BB0);
DEFINE_NAKED_JMP(void OnSCCharInfoReq(CNSSessionPc * _COMMA CPacket &), 0x4B5BA0);
DEFINE_NAKED_JMP(void OnSCExchangeReq(CNSSessionPc * _COMMA CPacket &), 0x4B9770);
DEFINE_NAKED_JMP(void OnSCWareHouseList(CNSSessionPc * _COMMA CPacket &), 0x4C5A40);
DEFINE_NAKED_JMP(void OnSCItemDelete(CNSSessionPc * _COMMA CPacket &), 0x4B8DD0);
DEFINE_NAKED_JMP(void OnSSFriendDelete(CNSSessionPc * _COMMA CPacket &), 0x4C7310);
DEFINE_NAKED_JMP(void OnSCFriendDelete(CNSSessionPc * _COMMA CPacket &), 0x4C3C80);
DEFINE_NAKED_JMP(void OnSCDropItemList(CNSSessionPc * _COMMA CPacket &), 0x4B8710);
DEFINE_NAKED_JMP(void OnSCAutoRunEnd(CNSSessionPc * _COMMA CPacket &), 0x4B66F0);
DEFINE_NAKED_JMP(void OnSCTameMobNameChange(CNSSessionPc * _COMMA CPacket &), 0x4B5D80);
DEFINE_NAKED_JMP(void OnSCRealmMapInfo(CNSSessionPc * _COMMA CPacket &), 0x4C6680);
DEFINE_NAKED_JMP(void OnSCPartyQuit(CNSSessionPc * _COMMA CPacket &), 0x4BBD20);
DEFINE_NAKED_JMP(void OnSCFriendAddReq(CNSSessionPc * _COMMA CPacket &), 0x4C3D30);
DEFINE_NAKED_JMP(void OnSCPartyInvite(CNSSessionPc * _COMMA CPacket &), 0x4BC5A0);
DEFINE_NAKED_JMP(void OnSCPcShopBuy(CNSSessionPc * _COMMA CPacket &), 0x4C4900);
DEFINE_NAKED_JMP(void OnSCGameEnter(CNSSessionPc * _COMMA CPacket &), 0x4B5520);
DEFINE_NAKED_JMP(void OnSCAliasCreate(CNSSessionPc * _COMMA CPacket &), 0x4B5030);
DEFINE_NAKED_JMP(void OnSCExchangeCancel(CNSSessionPc * _COMMA CPacket &), 0x4BA410);
DEFINE_NAKED_JMP(void OnSCCmdRename(CNSSessionPc * _COMMA CPacket &), 0x4C6620);
DEFINE_NAKED_JMP(void OnSCTeleportAdd(CNSSessionPc * _COMMA CPacket &), 0x4C3950);
DEFINE_NAKED_JMP(void OnISSkillUse(CNSSessionPc * _COMMA CPacket &), 0x4C3330);
DEFINE_NAKED_JMP(void OnISLogWrite(CNSSessionPc * _COMMA CPacket &), 0x4C3710);
DEFINE_NAKED_JMP(void OnISGMemoWrite(CNSSessionPc * _COMMA CPacket &), 0x4C34B0);
DEFINE_NAKED_JMP(void OnISCheckDoubleConnect(CNSSessionPc * _COMMA CPacket &), 0x4C36D0);
DEFINE_NAKED_JMP(void OnISQuestMobCheck(CNSSessionPc * _COMMA CPacket &), 0x4C3260);
DEFINE_NAKED_JMP(void OnISEventItemAdd(CNSSessionPc * _COMMA CPacket &), 0x4C3850);
DEFINE_NAKED_JMP(void OnISPVPItemAdd(CNSSessionPc * _COMMA CPacket &), 0x4C32A0);
DEFINE_NAKED_JMP(void OnISMemoWrite(CNSSessionPc * _COMMA CPacket &), 0x4C33C0);
DEFINE_NAKED_JMP(void OnISItemLootAll(CNSSessionPc * _COMMA CPacket &), 0x4C31F0);
DEFINE_NAKED_JMP(void OnISTameMobSave(CNSSessionPc * _COMMA CPacket &), 0x4C36B0);
#endif

};





#endif